### ISSUE TITLE
Correct scale of density plots with multiple groups

### ISSUE THREAD

**Issue by rizbicki** [ggobi/ggally#101]
Hi,

I want to use ggpairs to have a diagonal with density plots of each variable separated by a grouping variable. I'm not being able to get the right plots because of a scale issue. To illustrate my point, I'll use the following artificial dataset:

```
group=as.numeric(cut(runif(100),c(0,1/2,1),c(1,2)))
x=rnorm(100,group,1)
x[group==1]=(x[group==1])^2
y=2*x+rnorm(100,0,0.1)
data=data.frame(group=as.factor(group),x=x,y=y)
```

Using ggpairs, I get the following plot

```
library(ggplot2)
library(GGally)    
ggpairs(data,columns = 2:3,colour="group")
```

![x1bkz](https://cloud.githubusercontent.com/assets/10176589/9909951/059a8ee0-5c71-11e5-9b30-ec4a01987218.png)

Now, compare the top left plot to the density plot of variable x obtained using plain ggplot2:

```
ggplot(data, aes(x = x, colour = group)) + geom_density() 
```
![x6w8f](https://cloud.githubusercontent.com/assets/10176589/9909981/1e132ebe-5c71-11e5-8b04-4d4b9126fab5.png)

We can see that the y scale of the red and blue curves in ggpairs (the first figure) are not the same, which may lead to misleading conclusions. How can I correct this in ggpairs? Is this a bug?

**Comment by schloerke** [comment]
you are correct.  they are not displaying correctly. :-(

With the current CRAN release, please try the following...

```{r}


set.seed(1234)
group = as.numeric(cut(runif(100),c(0,1/2,1),c(1,2)))
x = rnorm(100,group,1)
x[group == 1] = (x[group == 1])^2
y = (2 * x) + rnorm(100,0,0.1)
data = data.frame(group = as.factor(group), x = x, y = y)

library(ggplot2)
library(GGally)    

# # bad example
# ggpairs(data,columns = 2:3,colour="group")


ggally_correct_diag_densityDiag <- function(data, mapping, ...) {
  # the color is corrected to fill by ggpairs
  # to get desired output with color, it is changed back here.
  if (! is.null(mapping$fill)) {
    mapping$colour = mapping$fill
    mapping$fill = NULL
  }
  
  ggplot(data, mapping) + geom_density(...) 
}

ggpairs(data, columns = 2:3, colour = "group", diag = list(continuous = "correct_diag_density"))

```
![screenshot 2015-09-16 13 45 18](https://cloud.githubusercontent.com/assets/93231/9913145/39f053f2-5c79-11e5-8c80-0a508e19516a.png)


Until the next release, you can leverage the eval process of ggpairs.  "ggally_FN_NAME" or "ggally_FN_NAMEDiag" are the naming conventions to follow.    The next release will allow for submission of custom functions directly such as:
```{r}
ggpairs(data, columns = 2:3, colour = "group", diag = list(continuous = ggally_correct_diag_densityDiag))
```

**Comment by schloerke** [comment]
the original motivation was to scale the densities so the y axis is good for the other plots.  I believe the densities were scaled independently. Therefore, the behavior is not as expected.

Thank you!

**Comment by rizbicki** [comment]
Thanks, that is great!
