### ISSUE TITLE
ggplot2 1.1.0

### ISSUE THREAD

**Issue by briatte** [ggobi/ggally#105]
A new version of ggplot2 will be [out soon](https://github.com/hadley/ggplot2/blob/master/NEWS.md). It breaks many different things in GGally--by which I mean, many of the tests now fail.

I would be very surprised if the new version definitely broke any of GGally's functions, but it sure does break quite a few tests right now (including several tests for `ggnetwork`, for instance).

PR #104 makes ggnet + ggnet2 compatible with ggplot2 1.1.0.

**Comment by schloerke** [comment]
Thank you for the update!  I'll pull it in a couple days.

**Comment by briatte** [comment]
Hi @schloerke 

Catching up on the repo, am I right to understand that development has shifted to the __ggplot2_upgrade_v_1_1__ branch? Got nothing particular to commit, just curious.

**Comment by schloerke** [comment]
I made it sound fancy, but I still want everything from dev.  I'll merge it in soon.  We'll shift it from dev to master before friday when the email goes out. (similar to ggplot2).

**Comment by schloerke** [comment]
Think it's fair to say that we should depend on the new ggplot2 only?  There are a lot of trickery things inside ggpairs and some small annoying things in ggally_* functions since the upgrade

**Comment by briatte** [comment]
Agreed.

**Comment by schloerke** [comment]
merged into dev. closing
