### ISSUE TITLE
ggparcoord: "uniminmax" scaling error when data frame columns contain only one single value

### ISSUE THREAD

**Issue by schmidtchristoph** [ggobi/ggally#120]
Dear ggally developers,

I found the above descriped issue when I attempted to plot a parallel coordinate plot using a data frame that contained columns that stored only one single value for all observations / rows.

Since I programmed a quick no bells and whistles fix I'll submit a pull request with the solution that worked for me. Maybe it is useful or maybe you can cherrypick something out of it.

Thank you for the work you put into developing and maintaining this package. It helps me a lot.

Best regards,
Christoph

**Comment by schloerke** [comment]
fixed in #122
