### ISSUE TITLE
scatmat doesn't like non-factor colour columns

### ISSUE THREAD

**Issue by bbolker** [ggobi/ggally#129]
This is a wish-list item/easy to work around, or a request for documentation enhancement, I guess ...

```
library("GGally")
data(flea)
scatmat(flea,columns=2:4,color="species")  ## fine
flea$species <- as.character(flea$species)
scatmat(flea,columns=2:4,color="species")
## Error in eval(expr, envir, enclos) : object 'colorcolumn' not found
packageVersion("GGally")  ## 1.0.0
```

The documentation *does* say "factor variable":

> color: an option to group the dataset by the factor variable and color them by different colors. Defaults to ‘NULL’

but I've become so lazy/used to the idea that character variables will Just Work that it would be nice if this worked too ...

**Comment by dicook** [comment]
Hi Ben,

Yes, the color column should be a factor. I’ll see if it is easy to make it work for continuous values. The complication is that correlation is calculated separately for each group so this would need to be decoupled. Also, ggscatmat is the function to use, scatmat is only supposed to be a supporting function, but we made it visible, maybe it should have been invisible to save confusion.

cheers,
Di

> On Jan 7, 2016, at 7:57 AM, Ben Bolker <notifications@github.com> wrote:
> 
> This is a wish-list item/easy to work around, or a request for documentation enhancement, I guess ...
> 
> library("GGally")
> data(flea)
> scatmat(flea,columns=2:4,color="species")  ## fine
> flea$species <- as.character(flea$species)
> scatmat(flea,columns=2:4,color="species")
> ## Error in eval(expr, envir, enclos) : object 'colorcolumn' not found
> packageVersion("GGally")  ## 1.0.0
> 
> The documentation does say "factor variable":
> 
> color: an option to group the dataset by the factor variable and color them by different colors. Defaults to ‘NULL’
> 
> but I've become so lazy/used to the idea that character variables will Just Work that it would be nice if this worked too ...
> 
> —
> Reply to this email directly or view it on GitHub.
> 

---------------------------
Di Cook
visnut@gmail.com

**Comment by bbolker** [comment]
my goodness that was quick!  in the meantime I found that custom-setting mappings in `ggpairs` is working better for what I'm doing ...

**Comment by dicook** [comment]
Ok %^)

> On Jan 7, 2016, at 8:12 AM, Ben Bolker <notifications@github.com> wrote:
> 
> my goodness that was quick! in the meantime I found that custom-setting mappings in ggpairs is working better for what I'm doing ...
> 
> —
> Reply to this email directly or view it on GitHub.
> 

---------------------------
Di Cook
visnut@gmail.com

**Comment by schloerke** [comment]
on cran now. v1.0.1
