### ISSUE TITLE
ggmatrix is doing strange things to axes when using the legends option

### ISSUE THREAD

**Issue by phipsgabler** [ggobi/ggally#135]
First, thank you for making this package, it's a really useful addition to ggplot2.

To the issue: I know that the docs say using the "legends" option is not recommeded, but I need to use it in some cases with `ggmatrix`. The problem is that adding legends seems to shift the axes and labels in strange ways:

```{R}
library(ggplot2)
library(GGally)

data <- data.frame(category=c(rep('+', 4), rep('-', 4)),
                   value=c(rnorm(4, 1), rnorm(4, 2)))

basic.plot <- ggplot(data, aes(x=category, y=value, colour=category)) +
    geom_point()

test.plots <- list(
    left=basic.plot + theme(legend.position='left'),
    right=basic.plot + theme(legend.position='right'), 
    top=basic.plot + theme(legend.position='top'),
    bottom=basic.plot + theme(legend.position='bottom')
)

try.plot <- function(plot) ggmatrix(
                               list(plot),
                               nrow=1, ncol=1,
                               legends=T)

try.plot(test.plots$left)
try.plot(test.plots$right)
try.plot(test.plots$top)
try.plot(test.plots$bottom)
```

Pictures of the different outputs are here:

![left](https://cloud.githubusercontent.com/assets/7878215/12352972/c0d71e6c-bb8a-11e5-8bff-fae33676564e.png)
![right](https://cloud.githubusercontent.com/assets/7878215/12352978/ca5e39ca-bb8a-11e5-88f2-719b8dd961a4.png)
(Note how the '-' and '+' are not where they should be).

![bottom](https://cloud.githubusercontent.com/assets/7878215/12352981/cc5ae5b6-bb8a-11e5-9d5e-d6e6251e7185.png)

The ploblem seems to be that when putting the legends to the left or right, the axis labels is shifted by the additional space needed for that; and when putting the legend at the bottom, the axis labels are repeated below it.

Putting the legend on the top seems to be the least harmful: 
![top](https://cloud.githubusercontent.com/assets/7878215/12352989/dcc95ec8-bb8a-11e5-8360-e19700c3d17d.png).

But also that sometimes repeats the y-labels, if it is high enough: 

![real](https://cloud.githubusercontent.com/assets/7878215/12352996/eb1120f6-bb8a-11e5-9f00-4114e4e4a13f.png)

Oh, and yes, I tried that plotting just `test.plots$left` and so on, without wrapping it in ggmatrix with `try.plot`, works normal and as expected, so it must be the effect of ggmatrix. So the "expected behaviour would be this: 
![ok](https://cloud.githubusercontent.com/assets/7878215/12353028/39017e14-bb8b-11e5-9f19-78b23a833962.png)

**Comment by schloerke** [comment]
Hi Philip,

Glad you like it!

So this is a (possibly) big can of worms of edge cases, unfortunately.  It is fixable, but it'll take some time to get it right.  

Lets talk situations.  From what I can see...
* If a legend is on the left or bottom, the axis should not be duplicated.
* If a legend is on the top or right, one axis should be shifted to align with the plot.

The plot's alignment with the other plots in the matrix will not be correct if a legend is printed. (unless all other plots print the same legend)

Does this seem right?

- Barret

**Comment by schloerke** [comment]
Other options.

* have a function to "steal" a legend from a plot and only print the legend in that plot location.  Such as a 2x2 matrix
<pre>
------------------------
| plotA, legendOfPlotB |
| plotB, plotC         |
------------------------
</pre>
```{r}
# something like this...
test.plots <- list(
    left = basic.plot1,
    right = basic.plot2, 
    top = ggally_legend_of_plot(basic.plot3),
    bottom = basic.plot4
)
ggmatrix(test.plots, nrow=2, ncol=2)
```

* "steal" a legend from one plot. plot the legend in the respective position. then print a regular (no legend) ggmatrix in the remaining area.
```
# ggmatrixPlotmatrix, legendOfSomePlotPosition
---------------------------
| plot1, plot2 |  "print  |
| plot3, plot4 |  legend" |
---------------------------

# ggmatrixPlotMatrix
# legendOfSomePlotPosition
------------------
| plot1, plot2   |
| plot3, plot4   |
|----------------|
| "print legend" |
------------------
```
```{r}
# something like this...
test.plots <- list(
    left = basic.plot1,
    right = basic.plot2, 
    top = basic.plot3,
    bottom = basic.plot4
)
ggmatrix(test.plots, nrow=2, ncol=2, legendPosition = "right", legendPlotPosition = 2)
```

I would love to drop the ``legends`` argument completely.

**Comment by phipsgabler** [comment]
Hi, 

sorry for responding with so much delay, I've been busy lately.

Yes, your three points are exactly summarizing the problem; here's all four plots at once:

![all](https://cloud.githubusercontent.com/assets/7878215/13216650/5c487ed2-d95d-11e5-97e1-1419de7cf183.png)

Probably not what anyone would want...

As to your alternative options: I really like the idea of "legend stealing", that would give the user complete control while removing the axis problem. Ideally, both variants you described could be generalized into one, if it was possible to define "multi-row/column cells" -- then the plot of the second option would just consist of three rows, with the last one being one cell spanning two columns:

```
-----------
| p1    p2 |
| p3    p4 |
| [ lgnd ] |
-----------
```

(and basically the same for putting the legend on the right).

If that would work, options like `legendPosition = "right"` would just be syntactic sugar for "extending" each cell into two, with the right one containing the stolen legend of the plot in the left one, that is, automatically converting

```
---------                      ---------------------------
| p1 p2 |        ------->      | p1 lgnd(p1) p2 lgnd(p2) |
| p3 p4 |                      | p3 lgnd(p3) p4 lgnd(p4) |
---------                      --------------------------- 
```

Unfortunately, I'm not really knowledgeable about ggplot2 and GGally internals, so I don't think I could implement anything useful for this... But I'm patient ;)

**Comment by schloerke** [comment]
I don't think it' be too hard to do a "right side" legend only.  I know there are benefits of having a legend on the bottom and rare cases the top or left, but that'd be no fun to implement on my end.  

I think having a legendPlotPosition arg to tell ggmatrix where to "steal" from would get us pretty far.  

First steps...
I like the idea of the extra plot position idea for the legends.  I think a generic function to take the legend of a ggplot2 object and print it as if it was a regular plot would be good to have. (would also be used for the line above this).  Then it would allow people full control (at least within ggmatrix).



Thank you for being patient!!

**Comment by schloerke** [comment]
#155

So this is a thing....

```{r}
pm <- ggpairs(
  iris, 1:2,
  mapping = ggplot2::aes(color = Species),
  upper = list(continuous = gglegend("points"))
)
```
![screen shot 2016-04-06 at 3 44 33 pm](https://cloud.githubusercontent.com/assets/93231/14330438/929560da-fc0e-11e5-9bfa-977762e163e9.png)

**Comment by schloerke** [comment]
The "right" location for a legend that would take up a full column will take some more time as it really messes with the internals of the ggmatrix print method.  I'm thinking I'll get it done this summer.  :-/  This is a while, but I have time set aside then. 

gglegend and grab_legend are added into the dev branch

**Comment by schloerke** [comment]
Hi @phipsgabler !

I have good news!  The changes below will be in the next release.

Check this out.... (I have removed the legends parameter completely with this change.)
```{r}
library(ggplot2)
library(GGally)

data <- data.frame(
  category = c(rep('+',  4), rep('-', 4)),
  value = c(rnorm(4, 1), rnorm(4, 2))
)

basic_plot <- ggplot(data, aes(category, value, colour = category)) + geom_point()

basic_plots <- list(
  basic_plot,
  basic_plot,
  basic_plot,
  basic_plot
)

try_plot <- function(plot_pos, title) {
  ggmatrix(basic_plots, nrow=2, ncol=2, legend = plot_pos, title = title)
}

try_plot(NULL, "No Legend")
```
![screen shot 2016-09-09 at 5 04 56 pm](https://cloud.githubusercontent.com/assets/93231/18402882/c033b76e-76af-11e6-9b89-64a216b9c21d.png)
```{r}
try_plot(2, "retrieve with single value")
```
![screen shot 2016-09-09 at 5 05 14 pm](https://cloud.githubusercontent.com/assets/93231/18402885/c5f833dc-76af-11e6-9c45-9c63684b1e0e.png)
```{r}
try_plot(2, "change sides") + theme(legend.position="left")
```
![screen shot 2016-09-09 at 5 05 23 pm](https://cloud.githubusercontent.com/assets/93231/18402892/caba1c50-76af-11e6-933c-2b1da132d4b9.png)
```{r}
try_plot(c(1,2), "retrieve with coordinates") + theme(legend.position = "bottom")
```
![screen shot 2016-09-09 at 5 05 32 pm](https://cloud.githubusercontent.com/assets/93231/18402896/ce9ecfb4-76af-11e6-8b3c-898524c15c5e.png)
```{r}
test_legend <- grab_legend(qplot(category, data = data, fill = category))
try_plot(test_legend, "provide custom legend")
```
![screen shot 2016-09-09 at 5 05 43 pm](https://cloud.githubusercontent.com/assets/93231/18402899/d3538c8e-76af-11e6-8bc6-8c59acd589cb.png)

**Comment by schloerke** [comment]
(will close when merged into master)

**Comment by schloerke** [comment]
in master branch.  closing.
