### ISSUE TITLE
Add GGally to new ggplot2 extensions website

### ISSUE THREAD

**Issue by briatte** [ggobi/ggally#140]
- https://github.com/ggplot2-exts/ggplot2-exts.github.io/
- https://ggplot2-exts.github.io/

**Comment by schloerke** [comment]
I'll wait until I see how he adds your issue.  ... Can't quite figure out what I'm suppose to add.  

Just copy/paste the vignettes?

**Comment by briatte** [comment]
> Just copy/paste the vignettes?

Was also my first thought, but it's actually pretty quick to just copy/paste one basic example of any function. I would recommend using one of yours, `ggpairs`.

**Comment by schloerke** [comment]
https://github.com/ggplot2-exts/ggplot2-exts.github.io/issues/32

**Comment by schloerke** [comment]
Closing due to inaction
