### ISSUE TITLE
non-square matrices

### ISSUE THREAD

**Issue by stevepowell99** [ggobi/ggally#15]
Is there any way to produce non-square matrices, i.e. to plot one set of variables against another? e.g. in survey research I might want to plot age, sex etc as background variables against foreground variables like political attitudes, and I don't want to see the background variables plotted against themselves in the same plot. So I would like to just see age, sex in the rows of the matrix and e.g. a set of attitudes variables in the columns.

**Comment by schloerke** [comment]
#63
