### ISSUE TITLE
wrap_fn_with_param_arg documentation

### ISSUE THREAD

**Issue by GustafRydevik** [ggobi/ggally#150]
I would appreciate it if the documentation for wrap_fn_with_param_arg could be updated, at least with some examples of how to use it in combination of ggpairs. I've got 15+ years experience of trawling R help files, and if I get stumped on something as simple as changing color or font size, most other users will be as well....

**Comment by schloerke** [comment]
Thank you for bringing this up! I'll add more examples in the docs.  

Notes: 
* remove mentions of "wrap_fn_with_param_arg" from ggpairs docs and only point to wrap
* add a ggpairs example using both wrap and wrapp

**Comment by schloerke** [comment]
Closed in #152 

Thank you for the feedback! Please let me know if there's anything else you'd like for me to include!

**Comment by schloerke** [comment]
on cran (version 1.1.0)
