### ISSUE TITLE
Plotting model coefficients with broom and ggplot2

### ISSUE THREAD

**Issue by larmarange** [ggobi/ggally#160]
Plotting model coefficients is a very common task (http://www.r-statistics.com/2010/07/visualization-of-regression-coefficients-in-r/)

The `broom` package offers a convenient `tidy` method, working for a large variety of models, to produce a tidy data frame with model estimates and confidence intervals, easy to use with `ggplot2`.

Therefore, would it be relevant to have a wrapper function for quick plotting the coefficients of a model, e.g. something like `ggcoef(model)`?

I have developped such function: https://github.com/larmarange/JLutils/blob/master/R/ggcoef.R
You can test it by installing the `JLutils` package.

Let me know if you think it could be relevant for `GGally`. If so, I would prepare a pull request.

Regards

**Comment by schloerke** [comment]
Sounds good to me!  Thank you for the example!

Requests:
* Make sure to add yourself in the DESCRIPTION 
* Please make a vignette 
  * Copy a .Rmd file in the vignettes folder. 
  * Can be a minimal copy paste of the examples, but a little more explanation never hurts ;-)
* Please submit to ``dev`` branch (not ``master``)

- Barret


Side note for JLutils, the example for ggcoef is broken when getting the tidy_detailed(...).  In ``.levels_and_labels``, ``Labels`` should be set to ``NULL`` before asking if ``labelled`` can be loaded.

**Comment by larmarange** [comment]
Thanks for the feedback.

I will prepare a pull request.


Joseph

2016-05-16 17:58 GMT+02:00 Barret Schloerke <notifications@github.com>:

**Comment by larmarange** [comment]
Done.

Thanks for the note regarding JLutils.

**Comment by schloerke** [comment]
on cran (version 1.1.0)

**Comment by larmarange** [comment]
thanks
