### ISSUE TITLE
Rotated axis in ggpairs ratio?

### ISSUE THREAD

**Issue by davidlorenz** [ggobi/ggally#165]
Thanks for creating such a useful package! It appears that there's some strange axis rotation going on when using the "ratio" plot to compare two discrete variables in the ggpairs function. E.g., in this subset of the mtcars data, I'd expect the "carb" vs. "cyl" cell in the lower middle to have three columns (one for each cyl) and 8 rows (one for each carb) (or is this a misunderstanding of the desired layout?)

    mtcars$cyl <- as.factor(mtcars$cyl)
    mtcars$carb <- as.factor(mtcars$carb)
    ggpairs(mtcars[,c("mpg", "cyl", "carb")], lower = list(discrete = "ratio"), showStrips = TRUE)
![rplot001](https://cloud.githubusercontent.com/assets/10579349/15340095/b136ea1a-1c55-11e6-9524-1b7ccfa92bd4.png)

Thanks!

**Comment by schloerke** [comment]
Thanks for the example! I'll look into this one tomorrow :-)

**Comment by schloerke** [comment]
closing issue. being solved in PR #166

**Comment by schloerke** [comment]
on cran (version 1.1.0)
