### ISSUE TITLE
ggcorr with geom and layout.exp causes right column to be clipped

### ISSUE THREAD

**Issue by WHMan** [ggobi/ggally#170]
```
library("GGally")
set.seed(123)
df <- data.frame(matrix(rnorm(100), nrow=10))
ggcorr(df, layout.exp=1, geom="circle")
ggcorr(df, layout.exp=1, geom="text")
```

Within the ggcorr function, setting both layout.exp to a value >0 and geom to "circle" or "text", causes the right column to be clipped.  
Thanks in advance for your help!

**Comment by schloerke** [comment]
solved in PR #171

**Comment by WHMan** [comment]
Wow! Very fast. Many thanks!

**Comment by schloerke** [comment]
on cran (version 1.1.0)
