### ISSUE TITLE
namespace ‘grid’ 3.2.3 is already loaded, but >= 3.3.0 is required

### ISSUE THREAD

**Issue by krz** [ggobi/ggally#174]
Hi,

I'm getting this error when updating to the newest CRAN version 1.1.0.
Is R >= 3.3.0 now a requirement?

**Comment by schloerke** [comment]
Fixed in 9a41b5c . I meant to match the max required version, which was 3.1.  I'm currently developing on R3.3.0, so I slipped when including a package version for grid (3.3.0).  

For now, please install from the master branch.

devtools::install_github("ggobi/ggally")

Thank you!
