### ISSUE TITLE
Having issues using ggpairs with knitr

### ISSUE THREAD

**Issue by hengrumay** [ggobi/ggally#177]
I keep getting this error while trying to knitr to html/pdf etc.

> |....................................................             |  80%
> label: unnamed-chunk-2 (with options) 
> List of 1
>  $ echo: logi TRUE
> 
> 
> Quitting from lines 35-43 (Untitled.Rmd) 
> Error in eval(expr, envir, enclos) : could not find function "ggpairs"
> Calls: <Anonymous> ... handle -> withCallingHandlers -> withVisible -> eval -> eval
> Execution halted

The snippet of code I have is as follows.
For some reason, ggpairs is not found... even though it can be called outside of Rmd document.

> 
> ### ```{r, echo=TRUE, warning=TRUE, cache=TRUE}
> library(datasets)
> library(knitr) 
> library(ggplot2)
> library(GGally)
> # # https://cran.r-project.org/web/packages/GGally/vignettes/ggpairs.html
> ### ```
> 
> ### ```{r, echo=TRUE} 
> ggpairs(mtcars, aes(color=am), lower = list(continuous= "smooth", size = .8, alpha = 0.25), 
title="mtcars" )  
> ### ```
> 

Additionally

> sessionInfo()
> R version 3.3.0 (2016-05-03)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.11.4 (El Capitan)
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] ggplot2_2.1.0 GGally_1.1.0 
> 
> loaded via a namespace (and not attached):
>  [1] colorspace_1.2-6 scales_0.4.0     plyr_1.8.3       htmltools_0.3.5  tools_3.3.0      gtable_0.2.0    
>  [7] yaml_2.1.13      Rcpp_0.12.5      reshape_0.8.5    rmarkdown_0.9.6  grid_3.3.0       digest_0.6.9    
> [13] munsell_0.4.3 
> 

I wonder if someone could help me troubleshoot this? Thanks in advance!
May

**Comment by schloerke** [comment]
I'll chat with you here, May: https://gitter.im/ggobi/ggally
