### ISSUE TITLE
Can't install GGally from CRAN

### ISSUE THREAD

**Issue by friendly** [ggobi/ggally#181]
Under R < R 3.3, attempting to install from CRAN fails.  This seems to have something to do with `grid`.  Transcript from R 3.2.5:

    > install.packages("GGally")
    Warning: dependency ‘grid’ is not available

      There is a binary version available but the source version is later:
           binary source needs_compilation
    GGally  1.0.1  1.1.0             FALSE

    installing the source package ‘GGally’

    trying URL 'http://cran.stat.sfu.ca/src/contrib/GGally_1.1.0.tar.gz'
    Content type 'application/x-gzip' length 5554699 bytes (5.3 MB)
    downloaded 5.3 MB

    * installing *source* package 'GGally' ...
    ** package 'GGally' successfully unpacked and MD5 sums checked
    ** R
    ** data
    *** moving datasets to lazyload DB
    ** inst
    ** preparing package for lazy loading
    Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
      namespace 'grid' 3.2.5 is already loaded, but >= 3.3.0 is required
    ERROR: lazy loading failed for package 'GGally'
    * removing 'C:/R/R-3.2.5/library/GGally'

    The downloaded source packages are in
            ‘C:\Users\friendly\AppData\Local\Temp\Rtmp2nCpHg\downloaded_packages’
    Warning messages:
    1: running command '"C:/R/R-3.2.5/bin/x64/R" CMD INSTALL -l "C:\R\R-3.2.5\library" C:\Users\friendly\AppData\Local\Temp\Rtmp2nCpHg/downloaded_packages/GGally_1.1.0.tar.gz' had status 1 
    2: In install.packages("GGally") :
      installation of package ‘GGally’ had non-zero exit status
    >

**Comment by friendly** [comment]
It does install OK from github:

   library(devtools)
   install_github("ggobi/ggally")

**Comment by schloerke** [comment]
Correct.

Sorry about the version mixup. I should have a new version posted on cran
before the end of the month.

**Comment by schloerke** [comment]
Since it's fixed on master, I'm going to close this issue.
