### ISSUE TITLE
ggsurv survival order and colours

### ISSUE THREAD

**Issue by dchiu911** [ggobi/ggally#185]
![rplot](https://cloud.githubusercontent.com/assets/8665632/17159025/2a0efcd6-534f-11e6-85c5-694d08b4db69.png)

In the plot above, there are many survival curves put together. In the top right plot however, the stratum `[3,4]` appears before `[1,3)` based on the survival order. This isn't ideal, as it causes readers to be confused with the colour scheme of the two plots below it.

The desired legend I would like to see would have`0` getting red, `[1,3)` getting green, `[3,4]` getting blue, with the survival curves correctly reflecting this.

Can this be disabled? Base R solutions would work, but I want to inquire about about a `gg` solution first.

**Comment by schloerke** [comment]
Hi Derek,

Great idea!  Can you post your code / data here?  It'll make it much easier for me to reproduce the issue.

Thank you,
Barret

**Comment by schloerke** [comment]
Ok, I think there's a solution.  This should work for you.

We can supply the colors that should be used to the `cens.col` and `surv.col` arguments.

```{r}
library(ggplot2)
library(GGally)
data(kidney, package = "survival")
sf.kid <- survival::survfit(Surv(time, status) ~ disease, data = kidney)
# remove PKD
sf.kid <- sf.kid[1:3]

ggsurv(sf.kid, cens.col = 'gg.def', surv.col = 'gg.def', main = "default cols")
```
![screen shot 2016-07-27 at 9 40 40 am](https://cloud.githubusercontent.com/assets/93231/17177251/8c71f9b6-53de-11e6-940f-96acce1c7c31.png)


To get the default ggplot2 colors...
```{r}
ggcols <- ggplot2::scale_color_discrete()$palette(3)
ggcols
# [1] "#F8766D" "#00BA38" "#619CFF"
scales::show_col(ggcols)
```
![screen shot 2016-07-27 at 10 00 19 am](https://cloud.githubusercontent.com/assets/93231/17177794/f52932b0-53e0-11e6-94bf-3b56e6b382f4.png)

```{r}
ggsurv(sf.kid, cens.col = rev(ggcols), surv.col = rev(ggcols), main = "reversed ggplot2 cols")
```
![screen shot 2016-07-27 at 10 02 54 am](https://cloud.githubusercontent.com/assets/93231/17177930/7a16da0e-53e1-11e6-81a2-81818b6635ce.png)

**Comment by dchiu911** [comment]
It doesn't work for me. There seems to be something different happening to `surv.col` than `cens.col`.

`ggsurv(sfit, surv.col = "gg.def", cens.col = "gg.def")`

![rplot](https://cloud.githubusercontent.com/assets/8665632/17185589/85b01e84-53e6-11e6-9cc7-0008e5126c57.png)

`ggcols <- ggplot2::scale_color_discrete()$palette(3)`

`ggsurv(sfit, surv.col = ggcols, cens.col = ggcols)`

![rplot01](https://cloud.githubusercontent.com/assets/8665632/17185753/30a5ecba-53e7-11e6-8a68-68e35d5b1174.png)

`ggsurv(sfit, surv.col = rev(ggcols), cens.col = rev(ggcols))`

![rplot02](https://cloud.githubusercontent.com/assets/8665632/17185959/0c1a4020-53e8-11e6-8c61-13529900ccab.png)

**Comment by schloerke** [comment]
I think that's a bug.  See if you can play around with the censor colors to
match the survival line colors for now.

Let me know how this works for you.

**Comment by dchiu911** [comment]
This gives me the correct colour match, but I would still want the order of the levels to be 0, [1,3), [3,4].

`ggsurv(sfit, surv.col = ggcols[c(1, 3, 2)], cens.col = ggcols[c(1, 2, 3)])`

![rplot03](https://cloud.githubusercontent.com/assets/8665632/17186424/009bdf72-53ea-11e6-8768-add564e994ec.png)
