### ISSUE TITLE
ggmatrix - add control over the proportion of different elements

### ISSUE THREAD

**Issue by talgalili** [ggobi/ggally#188]
This can be done in `layout` by using a larger matrix and having multiple cell contain the same number value. Since ggmatrix doesn't allow this, it produces outputs such as this:

![image](https://cloud.githubusercontent.com/assets/976006/17394378/787ba340-5a31-11e6-80ca-0d23119ccacb.png)

Source: http://stackoverflow.com/a/38761461/256662

Where we cannot have the heatmap get a larger piece of the plot in terms of proportion.

**Comment by schloerke** [comment]
Hi @talgalili,

I've been torn on this idea for a while.  I will add an argument for you to use.  I don't know how long it will stay as I will be heading towards using a facet'ed ggplot object to display a ggmatrix object.  

I think the current print method is very hacky and needs an update.  I'll prolly end up having two print methods in the end.

I'll post a PR here shortly!

- Barret

**Comment by schloerke** [comment]
This has been added to the dev branch.  It'll be included in the next release.  To install right now, 

```{r}
devtools::install_github("ggobi/ggally@dev")
```
