### ISSUE TITLE
Possible to make ggpairs (and others) work with ggsave?

### ISSUE THREAD

**Issue by puterleat** [ggobi/ggally#194]
At present,

```
saved plot <- data_frame(a=rnorm(100, b=rnorm(100)) %>% ggpairs
ggsave("plot.pdf")
```

Only saves the first density plot cell into plot.pdf. Is there a way of making this work?

**Comment by puterleat** [comment]
OK - with ref to this issue http://stackoverflow.com/questions/38061219/ggsave-ggpairs-plot-error, here's the solution:

```
pplt <- ggpairs(pdf)
grid.draw.gg <- function(x){
  print(x)
}
ggsave("mrc_report_plots/pairs.pdf", ppt)
```


Is there a way for users to avoid defining their own grid.draw.gg?

**Comment by schloerke** [comment]
I should be able to overwrite it with a grid.draw.ggmatrix method and
include it in GGally.

Thank you!
