### ISSUE TITLE
check variable types in ggpairs

### ISSUE THREAD

**Issue by AmeliaMN** [ggobi/ggally#197]
I often accidentally pass an entire dataset to ggpairs, forgetting that one or more of my variables are character variables or factors with many levels. It would be great if ggpairs checked for this before beginning computation. Either it could just throw an error, or print "character variable" in the boxes where plots would ordinarily go.

**Comment by schloerke** [comment]
Have an example dataset?  

How many levels does one of the columns have?

**Comment by AmeliaMN** [comment]
Well, I'm working on tidyverse-ifying the ISLR labs and was looking at the first one, which introduces pairs plots. I accidentally ran

```
library(ISLR)
library(GGally)
ggpairs(Auto)
```

As-is, the name variable is a factor with 304 levels, so of course `ggpairs()` hangs forever. If I remember to 

```
Auto %>%
   select(-name) %>%
   ggpairs()
```

it works fine. But, I'd prefer a better default for such an introductory lesson. 

Of course, the question is where to cut off the number of levels, but my guess is that 10 is probably the max you could really see, even if you only had two variables. Perhaps it could be a parameter with a default?

**Comment by schloerke** [comment]
I like the idea of throwing an error.

The threshold can be a parameter. So to change the parameter would be to allow for a potential hang knowingly.  

I'm still stuck on where the check should go.  Should it go in the `ggally_box` (and other methods respectively) or should it be in `ggpairs` where it will check before custom functions may be run even if the custom functions possibly won't hang.

**Comment by schloerke** [comment]
I think ggpairs might be the correct place.  It'd still be good to know if a high cardinality column was to be printed.

Thank you for the example and issue!

**Comment by schloerke** [comment]
```
 > library(ISLR)
Loading required package: ISLR
[1] TRUE
> library(GGally)
[1] TRUE
> 
> ggpairs(Auto)
Error in stop_if_high_cardinality(data, columns, cardinality_threshold) : 
  Column 'name' has more levels (304) than the threshold (15) allowed.
Please remove the column or increase the 'cardinality_threshold' parameter. Increasing the cardinality_threshold may produce long processing times
> 
> ggduo(Auto)
Error in stop_if_high_cardinality(data, columnsX, cardinality_threshold) : 
  Column 'name' has more levels (304) than the threshold (15) allowed.
Please remove the column or increase the 'cardinality_threshold' parameter. Increasing the cardinality_threshold may produce long processing times

```
