### ISSUE TITLE
ggpairs used within a loop

### ISSUE THREAD

**Issue by Sajnim** [ggobi/ggally#202]
Hi, 

Is it possible to use ggpairs within a loop. I've tried and it doesnt seem to work. 

I've pasted some code below as a reproducible example of what i cam trying to do. 

Just to note, with each iteration I load different datasets, and plot a modified version of the loaded dataset. 

Thanks in advance for your help,
Sajni

for (i in 1:10) {
    file_name <- paste("plot_", i, ".png", sep = "")
    png(filename = file_name, units = "cm", width =30, height = 35, res = 500, pointsize = 4)
    pm <- ggpairs(diamonds[1:100, 1:4],
                  upper = list(continuous = wrap("density", alpha = 0.5), combo = "box"),
                  lower = list(continuous = wrap("points", alpha = 0.3,    size=0.1)))
    pm
    dev.off()
}

**Comment by schloerke** [comment]
Fixed? Probably needs a ``print(pm)`` inside the png and dev.off

**Comment by Sajnim** [comment]
I closed the issue as I later thought this wasn't the place to ask questions. 
However print(pm) solves the problem. 
Thank You!
