### ISSUE TITLE
ggpairs demos not working

### ISSUE THREAD

**Issue by behrman** [ggobi/ggally#206]
With GGally 1.2.0 and R 3.3.1, I'm getting the following error when trying to work the ggpairs demos

```
> ggpairs(tips[, 1:3])
Error in FUN(X[[i]], ...) : 
  only defined on a data frame with all numeric variables
```

**Comment by schloerke** [comment]
I can not reproduce the error.  Can you please provide a `traceback()` after the error occurs and your `devtools::session_info()`?

Thank you,
Barret


```{r}
install.packages("GGally")
install.packages("ggplot2")
# quit and reopen R
```
```{r}
library(GGally)
data(tips, package = "reshape2")
ggpairs(tips[, 1:3])
# works
devtools::session_info()
```
```
Session info ------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, darwin13.4.0        
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Indiana/Indianapolis
 date     2016-10-25                  

Packages ----------------------------------------------------------------------
 package    * version     date       source                            
 colorout   * 1.1-2       2016-07-19 Github (jalvesaq/colorout@6d84420)
 colorspace   1.2-7       2016-10-11 cran (@1.2-7)                     
 devtools     1.12.0.9000 2016-10-17 Github (hadley/devtools@f0d1c7e)  
 digest       0.6.10      2016-08-02 cran (@0.6.10)                    
 GGally     * 1.2.0       2016-07-01 CRAN (R 3.3.1)                    
 ggplot2      2.1.0       2016-03-01 CRAN (R 3.3.1)                    
 gtable       0.2.0       2016-02-26 CRAN (R 3.2.3)                    
 labeling     0.3         2014-08-23 CRAN (R 3.1.1)                    
 magrittr     1.5         2014-11-22 CRAN (R 3.1.2)                    
 memoise      1.0.0       2016-01-29 CRAN (R 3.2.3)                    
 munsell      0.4.3       2016-02-13 CRAN (R 3.2.3)                    
 plyr         1.8.4       2016-06-08 CRAN (R 3.3.0)                    
 Rcpp         0.12.7      2016-09-05 cran (@0.12.7)                    
 reshape      0.8.5       2014-04-23 CRAN (R 3.0.2)                    
 reshape2     1.4.1       2014-12-06 CRAN (R 3.2.0)                    
 scales       0.4.0.9003  2016-10-16 Github (hadley/scales@d58d83a)    
 stringi      1.1.2       2016-10-01 cran (@1.1.2)                     
 stringr      1.1.0.9000  2016-10-19 Github (hadley/stringr@9963909)   
 withr        1.0.2       2016-06-20 CRAN (R 3.3.0)                    
```

**Comment by behrman** [comment]
Barret,

Below is the information you requested. I’m using a dev version of ggplot2.

Thanks,

Bill

> library(GGally)
> data(tips, package = "reshape2")
> ggpairs(tips[, 1:3])
Error in FUN(X[[i]], ...) : 
  only defined on a data frame with all numeric variables
In addition: Warning message:
`panel.margin` is deprecated. Please use `panel.spacing` property instead 
> traceback()
8: stop("only defined on a data frame with all numeric variables")
7: FUN(X[[i]], ...)
6: lapply(args, function(x) {
       x <- as.matrix(x)
       if (!is.numeric(x) && !is.complex(x)) 
           stop("only defined on a data frame with all numeric variables")
       x
   })
5: Summary.data.frame(list(t = numeric(0), b = numeric(0)), na.rm = FALSE)
4: `[.gtable`(pGtable, min(layoutTB):max(layoutTB), min(layoutLR):max(layoutLR))
3: pGtable[min(layoutTB):max(layoutTB), min(layoutLR):max(layoutLR)]
2: print.ggmatrix(x)
1: function (x, ...) 
   UseMethod("print")(x)
> devtools::session_info()
Session info --------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, darwin13.4.0        
 ui       RStudio (1.0.44)            
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2016-10-25                  

Packages ------------------------------------------------------------------------------
 package    * version    date       source                         
 assertthat   0.1        2013-12-06 CRAN (R 3.3.0)                 
 colorspace   1.2-7      2016-10-11 CRAN (R 3.3.0)                 
 devtools     1.12.0     2016-06-24 CRAN (R 3.3.0)                 
 digest       0.6.10     2016-08-02 CRAN (R 3.3.0)                 
 GGally     * 1.2.0      2016-07-01 CRAN (R 3.3.1)                 
 ggplot2      2.1.0.9001 2016-10-04 Github (hadley/ggplot2@5a18687)
 gtable       0.2.0      2016-02-26 CRAN (R 3.3.0)                 
 labeling     0.3        2014-08-23 CRAN (R 3.3.0)                 
 lazyeval     0.2.0      2016-06-12 CRAN (R 3.3.0)                 
 magrittr     1.5        2014-11-22 CRAN (R 3.3.0)                 
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.0)                 
 munsell      0.4.3      2016-02-13 CRAN (R 3.3.0)                 
 plyr         1.8.4      2016-06-08 CRAN (R 3.3.0)                 
 Rcpp         0.12.7     2016-09-05 CRAN (R 3.3.0)                 
 reshape      0.8.6      2016-10-21 CRAN (R 3.3.0)                 
 reshape2     1.4.2      2016-10-22 CRAN (R 3.3.0)                 
 scales       0.4.0      2016-02-26 CRAN (R 3.3.0)                 
 stringi      1.1.2      2016-10-01 CRAN (R 3.3.0)                 
 stringr      1.1.0      2016-08-19 CRAN (R 3.3.0)                 
 tibble       1.2        2016-08-26 CRAN (R 3.3.0)                 
 withr        1.0.2      2016-06-20 CRAN (R 3.3.0)

**Comment by schloerke** [comment]
Hi Bill,

Please use the dev version of GGally with the dev ggplot2.

```{r}
devtools::install_github("ggobi/ggally")
```

I'm planning on releasing GGally alongside the update of ggplot2.  ~ Nov 4th

Please let me know if you run into any issues or unexpected behavior.  (Don't have many testers besides me).  Hope you enjoy the new ggmatrix layout! There's a new 'legend' argument to add a ggplot2 legend.

Thank you,
Barret
