### ISSUE TITLE
Allow augmented columns in columnsX?

### ISSUE THREAD

**Issue by cpsievert** [ggobi/ggally#214]
That way you could have, for example, residuals vs fitted:

```r
ggnostic(mod, columnsY = ".resid", columnsX = ".fitted")
```

**Comment by schloerke** [comment]
I feel like that is the one edge case that's reasonable. I'd be happy to
add that calling ggduo directly as an example in ggnostic.

If there were more y columns, such as cooks distance, having fitted as the
X variable doesn't make sense. Or the reverse, Having residuals against
cooks distance doesn't make sense.

**Comment by cpsievert** [comment]
Ah, yea good point -- an example would be great, thanks!
