### ISSUE TITLE
Broken examples for ggpairs

### ISSUE THREAD

**Issue by nblumoe** [ggobi/ggally#217]
I tried running the examples from the documentation but encountered the following issue with GGally v1.2.0:

```
> # small function to display plots only if it's interactive
> p_ <- function(pm) {
+     if (interactive()) {
+         print(pm)
+     }
+     invisible()
+ }
> 
> data(tips, package = "reshape")
> pm <- ggpairs(tips[, 1:3])
> p_(pm)
 Show Traceback
 
 Rerun with Debug
 Error in FUN(X[[i]], ...) : 
  only defined on a data frame with all numeric variables In addition: Warning message:
`panel.margin` is deprecated. Please use `panel.spacing` property instead 
```

Had a quick look at recent changes, maybe https://github.com/ggobi/ggally/commit/87f364dcae2d1e6e2d3b1bed2ed7b69e06420f53 is related?

**Comment by schloerke** [comment]
This should be fixed with the latest GGally on cran now. V1.3.0.

I got accepted overnight.

**Comment by nblumoe** [comment]
Indeed, thank you!
