### ISSUE TITLE
Facet a custom plot in ggpairs

### ISSUE THREAD

**Issue by bdeonovic** [ggobi/ggally#218]
When I create a custom plot for ggpairs, is it possible to facet the plot? What would the syntax look like for this?

**Comment by schloerke** [comment]
Let's say you have a 2x2 plot matrix, `pm`. You'd like the plot in position
`pm[1,2]` to be a faceted ggplot2 plot?

**Comment by bdeonovic** [comment]
Yes

**Comment by schloerke** [comment]
There is no direct way to implement a facet of a single panel.  This should be handled with a custom function.

A red border was added to show it was a custom function.

```r
my_facet <- function(data, mapping, ...) { 
  # transfer the mapping position to X from Y and remove Y
  mapping$x <- mapping$y
  mapping$y <- NULL
  ggplot(data, mapping) + 
    geom_histogram(binwidth = 1/4, ...) + 
    coord_flip() + 
    facet_wrap(~ Species) + 
    theme(strip.background = element_rect(color = "red"))
}

pm <- ggpairs(iris, 4:5, upper = list(combo = my_facet))
pm
```
![screen shot 2016-11-15 at 5 10 33 pm](https://cloud.githubusercontent.com/assets/93231/20326401/9bbb47f4-ab56-11e6-99e0-72fa9a6ffb13.png)
