### ISSUE TITLE
strip position?

### ISSUE THREAD

**Issue by flying-sheep** [ggobi/ggally#219]
is there something like [`facet_grid`s](http://docs.ggplot2.org/current/facet_grid.html) “switch” parameter, able to flip the strips to the bottom and/or right?

if not, could you please add it?

**Comment by schloerke** [comment]
No, not right now.

I'll look into transferring all of the args for facet_grid

**Comment by flying-sheep** [comment]
cool. it’s not too natural to use the upper right triangle when only needing to show all combinations without the densities or so.

**Comment by schloerke** [comment]
Moving discussion to #223
