### ISSUE TITLE
Error in plotting scatter plot

### ISSUE THREAD

**Issue by minoo77777** [ggobi/ggally#221]
I want to plot a scatterplot using GGally package. My data frame contains these numbers
```
152861.1277	0.751206523	2013	1.35E+239	6.29E+03	2.00E-01	24.75857978	0.001103093	8.35E+04
127194.554	0.691661805	694	2.84E+238	6.29E+03	2.00E-01	14.97627887	0.000379999	5.26E+03
6.06E+04	5.34E-01	3.28E+02	5.16E+237	6.28E+03	2.00E-01	18.07714174	1.80E-04	1.01E+03
40410.08303	0.479646356	271	3.32E+237	6.28E+03	2.00E-01	32.25630782	0.000148763	1.89E+03
```
and I'll upload the hole dataframe
[example.txt](https://github.com/ggobi/ggally/files/650460/example.txt)
I wrote these code:
```
library(GGally)

    ggscatmat(df,alpha=0.8)  + 
  theme(legend.position="none")+
  labs(title = "Scatterplot")

```
but I faced this error

```
Error in if ((w[1] * sm + w[2] * cm + w[3] * dm + w[4]) < best$score) break : 
  missing value where TRUE/FALSE needed
```
I would be really grateful for your kind help.

**Comment by schloerke** [comment]
Hi @minoo77777,

The error lies with ggplot2.  It can't handle your fourth column with is **very** large.  If this column is log'ed, ``ggscatmat`` works as expected.

```r
dt <- read.table("example.txt")
dt_log <- dt
dt_log$V4 <- log(dt$V4)

ggscatmat(dt) # fails
ggscatmat(dt_log) # works
```

I've isolated it down to a tiny example.  I'm going to submit an issue with ggplot2.
