### ISSUE TITLE
change in axis label/strip styles - any way to revert to previous version?

### ISSUE THREAD

**Issue by bbolker** [ggobi/ggally#223]
I hate to say this, but I find the spiffy new axis label style in `ggpairs` (or I guess technically this is in `ggfacet.R`) disappointing relative to the old style. I definitely prefer the old style, as seen e.g. in [this SO question](http://stackoverflow.com/questions/28427572/manipulating-axis-titles-in-ggpairs-ggally) ...

Having strip labels on bottom/left is most important to me. I think it might be possible to achieve this by adding a `switch` argument to `ggfacet` and passing it through to `facet_grid` (and allowing it to be set/passed through from upstream) ... ideally, the labels would look more like regular axis labels, but that might be manageable my modifying the strip characteristics ... ?

I will work on this, but thought I would post it before I dug in, in case you are already working on this or have useful ideas (or want to jump in and solve the problem for me ...)

In the meantime I may 'solve' the problem by reverting to an earlier version of `ggpairs` ...

**Comment by schloerke** [comment]
How does this work for interface?  I am including the four plots with a regular ggplot2 facet_grid for comparison

```r
devtools::install_github("ggobi/ggally@ggfacet_params")
library(GGally)
library(ggplot2)
data(tips, package = "reshape")
qplot(total_bill, tip, data = tips, main = "qplot + facet_grid; default; switch = NULL") + facet_grid(sex ~ day, switch = NULL)
qplot(total_bill, tip, data = tips, main = "qplot + facet_grid; switch = 'x'") + facet_grid(sex ~ day, switch = 'x')
qplot(total_bill, tip, data = tips, main = "qplot + facet_grid; switch = 'y'") + facet_grid(sex ~ day, switch = 'y')
qplot(total_bill, tip, data = tips, main = "qplot + facet_grid; switch = 'both'") + facet_grid(sex ~ day, switch = 'both')
```
<img width="1015" alt="screen shot 2017-01-16 at 10 35 10 pm" src="https://cloud.githubusercontent.com/assets/93231/22006886/bba29b32-dc3c-11e6-8a5d-b678651a51b3.png">
<img width="1015" alt="screen shot 2017-01-16 at 10 35 38 pm" src="https://cloud.githubusercontent.com/assets/93231/22006889/bfbcfb18-dc3c-11e6-80a8-3d6aaf3f8131.png">
<img width="1015" alt="screen shot 2017-01-16 at 10 35 55 pm" src="https://cloud.githubusercontent.com/assets/93231/22006900/cc2f79e8-dc3c-11e6-9888-eb280e6dbce8.png">
<img width="1015" alt="screen shot 2017-01-16 at 10 36 06 pm" src="https://cloud.githubusercontent.com/assets/93231/22006904/d391abfc-dc3c-11e6-82de-95e4755675b9.png">




```r
ggpairs(tips, c(1,3,2), mapping = aes(color = sex), switch = NULL, title = "ggpairs; default; switch = NULL")
ggpairs(tips, c(1,3,2), mapping = aes(color = sex), switch = 'x', title = "ggpairs; default; switch = 'x'")
ggpairs(tips, c(1,3,2), mapping = aes(color = sex), switch = 'y', title = "ggpairs; default; switch = 'y'")
ggpairs(tips, c(1,3,2), mapping = aes(color = sex), switch = 'both', title = "ggpairs; default; switch = 'both'")
````
<img width="1015" alt="screen shot 2017-01-16 at 10 37 06 pm" src="https://cloud.githubusercontent.com/assets/93231/22006909/dd96b9e4-dc3c-11e6-96cc-9d9d1929e6e7.png">
<img width="1015" alt="screen shot 2017-01-16 at 10 37 23 pm" src="https://cloud.githubusercontent.com/assets/93231/22006913/ddd442c8-dc3c-11e6-9063-5346c6f54da2.png">
<img width="1015" alt="screen shot 2017-01-16 at 10 37 36 pm" src="https://cloud.githubusercontent.com/assets/93231/22006912/ddc9930a-dc3c-11e6-8a05-3a6f355bc1ca.png">
<img width="1015" alt="screen shot 2017-01-16 at 10 38 33 pm" src="https://cloud.githubusercontent.com/assets/93231/22006914/ddd513ec-dc3c-11e6-9ff0-fbd657632498.png">

**Comment by schloerke** [comment]
Looking at the other variables in ggplot2::facet_grid, they don't make sense for the ggmatrix being produced.  I added the switch param to ggmatrix, ggpairs, and ggduo.

**Comment by schloerke** [comment]
@bbolker Downgrading is no fun as there are a lot of ggplot2 dependencies that would have to be downgraded as well.  Hopefully we can get a solution here.

**Comment by bbolker** [comment]
this is amazing response time, and certainly an improvement. Do you think there's a way to hack/trick ggpairs into making the strip labels look like proper axis labels (i.e. no gray background [probably easy], plotted *outside* (below/to left of) axis tick labels rather than inside [??])

**Comment by schloerke** [comment]
At this point, it's a ggplot2 object.  So we can add themes to make the strip change colors.


```r
library(ggplot2)
data(tips, package = "reshape")
pm <- load_all(); ggpairs(tips, c(1,3,2), mapping = aes(color = sex), switch = "both")
pm + theme(strip.background = element_rect(fill = "white"))
```
<img width="1015" alt="screen shot 2017-01-16 at 11 07 10 pm" src="https://cloud.githubusercontent.com/assets/93231/22007415/88a25066-dc40-11e6-8b0f-6f301927f8c3.png">

**Comment by schloerke** [comment]
As for the order of display, that's a ggplot2 issue?  Or should GGally do this automatically with no option to change...?

**Comment by schloerke** [comment]
I can't think of any case where it would be better to have the label inside the axis ticks.

**Comment by schloerke** [comment]
@bbolker Can you think of any reason why we shouldn't do switch the position?  If so, I'll add it in.

Also, the param name might change as ggplot2 is moving from "switch" (v2.1.0) to "strip.position" (v2.2.0).  I may end up using "label_position".

**Comment by schloerke** [comment]
Ha! I got it.  I'll add this in as an example somewhere.  For now I am going to close the issue. 😄 

```r
ggpairs(tips, c(1,3,2), mapping = aes(color = sex), switch = "both") + 
  theme(
    strip.background = element_rect(fill = "white"), 
    strip.placement = "outside"
  )
```
<img width="1015" alt="screen shot 2017-01-16 at 11 39 47 pm" src="https://cloud.githubusercontent.com/assets/93231/22008004/2a25fb3c-dc45-11e6-9671-54f88d1e358e.png">

**Comment by psychelzh** [comment]
How about adding this example to the document of `ggpairs()`?
