### ISSUE TITLE
Not really an issue... just FYI

### ISSUE THREAD

**Issue by fderyckel** [ggobi/ggally#225]
See the message I got trying to install ggally today

```
> devtools::install_github("ggobi/ggally")
Skipping install of 'GGally' from a github remote, the SHA1 (4ed1c3bc) has not changed since last install.
  Use `force = TRUE` to force installation
```

**Comment by schloerke** [comment]
Yup.  `devtools::install_github()` records the sha1 number at the time of install.  This way it won't try to reinstall the same exact package if it has the same sha1.

**Comment by fderyckel** [comment]
I see. I didn't know that.  Thank you for your time and the great package!
I really love it.

2017-02-28 18:09 GMT+02:00 Barret Schloerke <notifications@github.com>:
