### ISSUE TITLE
ggpairs correlation aestetics

### ISSUE THREAD

**Issue by jcberny** [ggobi/ggally#226]
Hi there,
I was wondering if it would be possible to change the number of decimals shown in the correlations, as well as to remove the Corr: before the correlations, as it seems redundant. 

With regards,
Jorge

**Comment by schloerke** [comment]
Hi Jorge,

For now, it is probably easiest to make your own function.  I will try to make the default correlation better in the future.

If you are not using colors, I recommend this solution: https://github.com/ggobi/ggally/issues/139. In this issue, I created a "my_custom_cor" function to produce numbers with stars with varying text size.

Please let me know if this helps your situation.

Best,
Barret

**Comment by schloerke** [comment]
I work on a correlation function for the next dev cycle.  Closing for now

Best,
Barret
