### ISSUE TITLE
Correlation plot with grouped data

### ISSUE THREAD

**Issue by ashishdamania** [ggobi/ggally#227]
Thanks for making ggally package. 
Is it possible to extend function "my_custom_cor"  in  #139 with graph in 
http://ggobi.github.io/ggally/#ggallyggscatmat ?
Basically, I want to show asterisk for significant p-values. I can get it for overall correlation using your "my_custom_cor" function but not for groups within that data.
So in your example in link above , I would like to see asterisk for each species using "symnum" function. 
Any pointers on how it can be done?
Thanks again!

**Comment by schloerke** [comment]
Using a custom function, like 'my_custom_cor', can only really be done with ggpairs, ggduo, or ggmatrix.  ggscatmat is a fast / rigid plot that can't really be customized.  

I would try to recreate your current ggscatmat plot using ggpairs.

**Comment by schloerke** [comment]
Glad you like the package! I'm going to close this issue.

**Comment by deepthoughts** [comment]
Sorry for commenting on closed issue.
Actually I tried it using ggpairs but I cannot get it any further.


#To print the group names along with the correlation
```
ggpairs(flea, columns=2:4,diag = NULL,upper = list(continuous = wrap(my_custom_cor)), axisLabels = "blank",ggplot2::aes(colour = species),size=10) +theme(text = element_text(size=10),axis.text.x=element_text(angle=45,hjust=1,size=10)) + theme_bw()
```

**Comment by schloerke** [comment]
ah... so the 'my_custom_cor' function is not a generalized function.  When the cor.test(x,y) is performed, it has no notion of groups (color in your case).  So the function is only useful for displaying the overall correlation.

**Comment by schloerke** [comment]
The function does give you a 'playground' to calculate the correlation given the color groups.  This is where you can alter it or create a new function to display what you want.

I do know I need to work on a better correlation display function for the future.

**Comment by deepthoughts** [comment]
Thanks for such rapid response. 
I will try to see If I can customize "my_custom_cor" to get my desired output.

**Comment by deepthoughts** [comment]
Here is what I got so far:
I see that using cor function gives me the correlation values but I am not sure what I need to modify to get asterisk along with the correlation values. As far as I know, cor only gives you correlation coefficient. Not sure if this is right path to get my output. 
Thanks for your input so far. 

```
ggpairs(flea, columns=2:4,diag = NULL,upper = list(continuous = wrap('cor', method = "kendall",size=4,alignPercent=0.9)), axisLabels = "blank",ggplot2::aes(color = species),size=10) +theme(text = element_text(size=10),axis.text.x=element_text(angle=45,hjust=1,size=10)) + theme_bw()
```


![screen shot 2017-04-22 at 12 12 30 pm](https://cloud.githubusercontent.com/assets/3029968/25306549/06e04672-2755-11e7-8c70-a7d6e5d61a7a.png)

**Comment by schloerke** [comment]
Could you please provide your solution here when you're done? I'd like to
include as many desirable features as possible.

Thank you!

**Comment by mwliang** [comment]
Dear @schloerke,

Thank you so much for making ggally package, also sharing the code (https://github.com/ggobi/ggally/issues/139), it's really useful and helpful. 

I have the similarly above-mentioned situation! I've tried a few times, around two days, but I failed.
I am looking forward your further  results.  Thanks a lot, man, great job!
Have a great weekend!

Best,
Maowei Liang

**Comment by luqman457** [comment]
When I try ggscatmat, it gives following error;

Error in match.names(clabs, names(xi)) : 
  names do not match previous names

Can you please help me solve this problem?

**Comment by schloerke** [comment]
@luqman457 please submit a **new** issue with `reprex` code so I can debug your issue

```r
reprex::reprex({
  # code
})
```

**Comment by luqman457** [comment]
@schloerke I don't understand. What is reprex::reprex? what kind of code should I assign to my issue? I am very new to all this. I solely joined this forum while finding solution for this problem. I have been using ggpairs for quite sometime. This time I was thinking about visualizing my data with ggscatmat as it's more clearer and the contents in the back (in histograms) don't get hidden in the picture. I am using the same file for ggscatmat that I used for ggpairs.
Thank you.

**Comment by schloerke** [comment]
@luqman457 

A reprex is a reproducible example.  The code is run in an isolated R session to make sure I (or someone else) can reproduce it on my end.   GitHub link: https://github.com/tidyverse/reprex

An example would be:

--------

If I ran this R code in the console... 
```r
reprex::reprex({
  set.seed(1234)
  a <- runif(5)
  print(a)
})
```
It would put the code below in my computer's 'clipboard'
<pre>
``` r
set.seed(1234)
a <- runif(5)
print(a)
#> [1] 0.1137034 0.6222994 0.6092747 0.6233794 0.8609154
```
</pre>

which is formats nicely in GitHub like
``` r
set.seed(1234)
a <- runif(5)
print(a)
#> [1] 0.1137034 0.6222994 0.6092747 0.6233794 0.8609154
```


----


Please only put the necessary code to reproduce your error within the `reprex::reprex` function.

Please put this in a [new issue](https://github.com/ggobi/ggally/issues/new) as your error does not involve correlation plots.

**Comment by luqman457** [comment]
Alright, I shall try. Thanks.
