### ISSUE TITLE
Is it possible to facet_wrap a ggpairs plot?

### ISSUE THREAD

**Issue by puterleat** [ggobi/ggally#233]
What I'd like to do is create 2 panels, with a ggpairs plot for each of my groups? Is this possible? Simply writing `ggpairs(...) + facet_wrap(~group)` creates an error.

**Comment by schloerke** [comment]
Hi @puterleat,

Thank you for the suggestion! There are many many edge cases that will be hit very quickly, so I do not see this be added in the near future.  

Currently, I think that would be best done by combining GGally::ggmatrix objects with gridExtra.  A direct limitation is that color and factor levels will not transfer between plots that contain different data.

However, this should get you closer to your goal...

``` r

library(GGally)
library(gridExtra)

wrap_ggmatrix <- function(pm, columns, nrow, ncol, ..., newpage = FALSE) {
  
  dt_list <- split(pm$data, pm$data[columns])
  
  matrix_list <- lapply(seq_along(dt_list), function(dt_item_num) {
    dt_item <- dt_list[[dt_item_num]]
    # copy for clarity
    pm_item <- pm
    # insert data of current subset
    pm_item$data <- dt_item
    
    pm_item$title <- names(dt_list)[dt_item_num]
    
    # make gtable from ggmatrix
    ggmatrix_gtable(pm_item)
  })
  
  # print it using gridExtra
  grid.arrange(grobs = matrix_list, nrow = nrow, ncol = ncol, ..., newpage = newpage)
}


pm <- ggpairs(iris, 3:5)
wrap_ggmatrix(pm, "Species", nrow = 1, ncol = 3)
```
![screen shot 2017-06-07 at 1 04 47 pm](https://user-images.githubusercontent.com/93231/26891165-14876b60-4b82-11e7-88ff-424563524ba2.png)


```r
pm <- ggpairs(reshape::tips, c(1, 2, 5, 6))
wrap_ggmatrix(pm, c("sex", "smoker"), nrow = 2, ncol = 2)
```
![screen shot 2017-06-07 at 1 05 08 pm](https://user-images.githubusercontent.com/93231/26891164-11ebdeb8-4b82-11e7-93cb-a45852715da7.png)


```r
  # don't drop the species values.... must be done with custom code
  no_drop_box <- function(...) {
    ggally_box_no_facet(...) + ggplot2::scale_x_discrete(drop = FALSE)
  }
  no_drop_bar_diag <- function(...) {
    ggally_barDiag(...) + ggplot2::scale_x_discrete(drop = FALSE)
  }
  pm <- ggpairs(
    iris, 3:5, 
    diag = list(discrete = no_drop_bar_diag), upper = list(combo = no_drop_box)
  )
  wrap_ggmatrix(pm, "Species", nrow = 1, ncol = 3)
```
![screen shot 2017-06-07 at 1 30 44 pm](https://user-images.githubusercontent.com/93231/26892224-92a1137c-4b85-11e7-8fe0-47646ad59fef.png)




If you are looking to keep color consistent, I recommend using a manual color scale.  https://stackoverflow.com/questions/6919025/how-to-assign-colors-to-categorical-variables-in-ggplot2-that-have-stable-mappin provides a good example to keep colors consistent.  Depending on the plot, you could `scale_fill_manual` or `scale_color_manual`.

Hope this helps.

Best,
Barret

**Comment by puterleat** [comment]
Thankyou so much for your very thorough response – very generous of your time.  I did wonder if the implementation would just be too icky to be worth it! I'll stick to combing plots as you suggest.

**Comment by puterleat** [comment]
p.s.... I almost feel like this information should be captured somewhere and not hidden in a closed issue? Perhaps you should add this to the docs!
