### ISSUE TITLE
Changing family font does not change family font of labels

### ISSUE THREAD

**Issue by angelini75** [ggobi/ggally#242]
I used the following code to change the font family of a scatterplot 
```
ggscatmat(data, columns = 1:9,  alpha=0.15)+  
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5),
        text = element_text(size = 13, family = "serif"),
        title = element_text(family = "serif")) 
```
This is the result
![rplot](https://user-images.githubusercontent.com/1261131/29309108-9cd0f746-81a8-11e7-85c1-2f728a417712.png)

What I want to obtain is this
![rplotserif](https://user-images.githubusercontent.com/1261131/29309152-ca240404-81a8-11e7-85cb-5e0a10f401fe.png)

To do so, I changed the `ggscatmat` function as follows,
```
function (data, columns = 1:ncol(data), color = NULL, alpha = 1, 
                        corMethod = "pearson") 
{
  data <- data
  data.choose <- data[columns]
  dn <- data.choose[sapply(data.choose, is.numeric)]
  if (ncol(dn) == 0) {
    stop("All of your variables are factors. Need numeric variables to make scatterplot matrix.")
  }
  if (ncol(dn) < 2) {
    stop("Not enough numeric variables to make a scatter plot matrix")
  }
  a <- uppertriangle(data, columns = columns, color = color, 
                     corMethod = corMethod)
  if (is.null(color)) {
    plot <- scatmat(data, columns = columns, alpha = alpha) + 

#here I include the family font.
      geom_text(data = a, aes_string(label = "r"), colour = "black", family = "serif") 
  }
  else {
    plot <- scatmat(data, columns = columns, color = color, 
                    alpha = alpha) + geom_text(data = a, aes_string(label = "r", 
                                                                    color = "colorcolumn")) + labs(color = color)
  }
  factor <- data.choose[sapply(data.choose, is.factor)]
  if (ncol(factor) == 0) {
    return(plot)
  }
  else {
    warning("Factor variables are omitted in plot")
    return(plot)
  }
}
```

Maybe it could be included as standard. Also, would be more appropriate if the hyphen (-) is replaced by the minus symbol or the n-dash symbol (–).
 
Kind regards,
Marcos

**Comment by schloerke** [comment]
Hi Marcos,

This can currently be fixed using ggplot2's `aes()` function.  geom_text uses the aesthetic 'family', so it may be added afterwards.  http://ggplot2.tidyverse.org/reference/geom_text.html#aesthetics

I'll keep note of the confusion that ggscatmat has for future issues!

If you'd like full customization, please look at using `ggpairs`.

Best,
Barret

``` r
library(ggplot2)
library(GGally)
# regular
ggscatmat(iris, 1:4)
```

![](http://i.imgur.com/hpCLXf7.png)

``` r
# serif
ggscatmat(iris, 1:4) + aes(family = "serif")
```

![](http://i.imgur.com/b2MAKUU.png)
