### ISSUE TITLE
Printing progress bars in ggpairs

### ISSUE THREAD

**Issue by VectorPosse** [ggobi/ggally#243]
For R Markdown documents and R notebooks, it would be nice to have a function argument in ggpairs to suppress printing of the progress bars.

A workaround is noted here:

https://stackoverflow.com/questions/41577362/suppress-ggpairs-messages-when-generating-plot

But it would be easier not to have to invoke a separate print method just to turn off the progress bars.

**Comment by schloerke** [comment]
Would a global options setting work? 

Thinking something like `options("ggmatrix.progress.bar" = FALSE)`

**Comment by schloerke** [comment]
Or should this be addressed to RStudio Journals only.  I don't know of an execution flag within RStudio for a Journal chunk.

**Comment by VectorPosse** [comment]
As a teacher of stats, I'm always on the lookout for things that will be easy for my students. I don't want a lot of cognitive overhead. So global options would not be a good solution for my use cases.

Rather than some kind of flag that would get recognized by RStudio, why not just a simple argument that tells ggpairs to print or not print the progress bars? progress = TRUE or progress = FALSE. Something like that.

**Comment by schloerke** [comment]
I've used the `progress` argument.  

If you'd like:
```r
devtools::install_github("ggobi/ggally@dev")
```

Will comment again when it's on CRAN.  Planning on mid November.

**Comment by VectorPosse** [comment]
That's awesome! Thank you so much!
