### ISSUE TITLE
JAMOVI correlation plot statistics issues

### ISSUE THREAD

**Issue by BTunca** [ggobi/ggally#255]
Hi,

When plotting the correlation matrix with the statistics option, coefficient values appear in 2, 3, or 4 digits after the comma. I observed the same issue in different datasets. Here is the excerpt from the BigFive dataset:

![capture](https://user-images.githubusercontent.com/27208030/33065383-fe483780-cea8-11e7-974e-46e73038f26f.PNG)

With Thanks,

**Comment by schloerke** [comment]
The current implementation of ggally_cor has 3 significant digits (not total digits).  https://github.com/ggobi/ggally/blob/0dc3283acfbf84da8882575b04e3db90607183c0/R/gg-plots.R#L406-L409

For two significant digits appearing, I believe `signif` removes the trailing zeros.  


I see on Wiki that trialing zeros are considered significant.  Seems fair to add trialing zeros in.
https://en.wikipedia.org/wiki/Significant_figures#Concise_rules

So fix the trailing significant zeros?

**Comment by jonathon-love** [comment]
hi,

i just thought i'd add another perspective.

with [jamovi](https://www.jamovi.org) we generally format to significant figures &ndash; *except* when the value is constrained between 0 and 1 &ndash; then we use a fixed number of decimal places.

i.e. i think with correlation coefficients: 1.00, 0.50, 0.05 is preferable to 1.00, 0.500, 0.0500

cheers

jonathon
