### ISSUE TITLE
Having many ggpairs plots side-by-side in a grid?

### ISSUE THREAD

**Issue by heoa** [ggobi/ggally#256]
I am trying to plot many ggpairs plots side-by-side. I could find this ticket, https://github.com/ggobi/ggally/issues/125: I tried it 

```
g20 <- ggpairs(...)
g21 <- ggpairs(...)
grid.newpage()

pushViewport(viewport(layout=grid.layout(1,2)))
vp1 <- viewport(
  layout.pos.col=1,
  layout.pos.row=1
)
vp2 <- viewport(
  layout.pos.col=2,
  layout.pos.row=1
)

pushViewport(vp1)
# use new boolean
print(g20, gridNewPage = FALSE)
popViewport()

pushViewport(vp2)
plot(g21, vp = vp2)
popViewport()
```
but causing the error

```
Error in grid.Call.graphics(C_unsetviewport, as.integer(n)) : 
  cannot pop the top-level viewport ('grid' and 'graphics' output mixed?)
```
and I also tried
```
g1 <- ggpairs(...)
g2 <- ggpairs(...)
g3 <- ggpairs(...)
plot_grid(g1, g2, g3, nrow=3)
```
but it failed causing the error
```
Error in plot_to_gtable(x) : 
  Argument needs to be of class "ggplot", "gtable", "grob", "recordedplot", or a function that plots to an R graphicsdevice when called, but is a ggggmatrix
```
so the question:

**How can I plot many ggpairs plots side-by-side?**

**Comment by schloerke** [comment]
Correct.

I am missing a function definition that ggplot2 has:
```r
grid.draw.ggmatrix <- function(x, recording = TRUE) {
  print(x)
}
```

This will allow gridExtra to arrange plots like normal ggplot2 plots.
```r
gridExtra::grid.arrange(g1, g2, g3, nrow = 3)
```

You could also call ``ggmatrix_gtable`` to produce gtable objects that cow_plot understands.
```r
plot_grid(
  ggmatrix_gtable(g1),
  ggmatrix_gtable(g2),
  ggmatrix_gtable(g3),
  nrow = 3
)
```

I'll add the grid.draw function to the package, but I can not provide any help to the cow_plot package as they do not use s3 methods.

- Barret

**Comment by heoa** [comment]
Thank you, Barrett. That worked perfectly +1 :)
