### ISSUE TITLE
How to scale strip size

### ISSUE THREAD

**Issue by sbihorel** [ggobi/ggally#257]
Hi,

Is there a way to control the size of the panel strips in ggpairs?

Playing with theme text size and lineheight has little to no effect.

```
require(GGally)
require(ggplot2)

data(flea)

png('test-%03d.png', width = 6, height = 6, unit= 'in', res = 300)
p1 <- ggpairs(flea, title = 'mytitle', switch = 'both')
p2 <- ggpairs(flea, title = 'mytitle')
print(p1 + theme(strip.placement = 'outside', text = element_text(size = 5)))
print(p1 + theme(strip.placement = 'outside', text = element_text(size = 8)))
print(p2 + theme(text = element_text(size = 8, lineheight = 1)))
print(p2 + theme(text = element_text(size = 8, lineheight = 2)))
dev.off()
```

**Comment by schloerke** [comment]
When I run it on my computer, I see the text sizes work.  

I believe ggplot2 element_text's lineheight requires multiple lines in the grouping variable.  It describes the distance between multiple lines within a strings.  With flea groups only being one line, I believe it's working as expected.  We can update them to have multiple lines though, like the example below.

``` r
require(GGally)
#> Loading required package: GGally
require(ggplot2)
#> Loading required package: ggplot2

data(flea)

new_size = 10
new_line_height = 10
col_labels <- c("\nspecies\n", "\ntars1\n", "\ntars2\n")

# png('test-%03d.png', width = 6, height = 6, unit= 'in', res = 300)
p1 <- ggpairs(flea, 1:3, title = "mytitle", switch = "both")
p2 <- ggpairs(flea, 1:3, title = "mytitle", columnLabels = col_labels)
print(p1 + theme(strip.placement = "outside", text = element_text(size = 5)))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/lChRlHt.png)

``` r
print(p1 + theme(strip.placement = "outside", text = element_text(size = new_size)))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/bhGGroM.png)

``` r
print(p2 + theme(text = element_text(size = new_size, lineheight = 1)))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/tWyFpGB.png)

``` r
print(p2 + theme(text = element_text(size = new_size, lineheight = new_line_height)))
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```

![](https://i.imgur.com/GH3EjA8.png)

**Comment by schloerke** [comment]
help from example: https://stackoverflow.com/questions/17825201/is-there-a-way-to-increase-the-height-of-the-strip-text-bar-in-a-facet

**Comment by sbihorel** [comment]
Hi, 
Comparing plots #1 and #2, it appears me that the strip width does not increase proportionally to the text size. To my eyes, there is proportionally more empty space below and above the strip text in plot #1 compared to plot #2. Do you agree or it is just my eyes which are tricking me?

I understand your explanation about lineheight. I have read the example before posting and try to implement this suggestions. This did not work for me as my concern is minimize the amount of empty space in the strip rather than increasing it.

**Comment by schloerke** [comment]
@sbihorel 

```
Comparing plots #1 and #2, it appears that the strip width/height does not increase proportionally to the text size.
```
Correct.  The strip height does not change according to the text size.  

```
There is proportionally more empty space below and above the strip text in plot #1 compared to plot #2
```
I believe this is correct as well.   

-------------
It would make sense it is non linear if there is some static width/height, plus font information.  

I believe the height and width have a minimal margin around the strip text that can not currently be reduced.

At this point, I am going to have to refer to you to the ggplot2 documentation. Unfortunately, this is not a ggplot2 issue, rather a ggplot2 issue in how it generates it's strips.

I've made an issue on your behalf and hopefully they can answer it.

**Comment by schloerke** [comment]
@sbihorel 
This ggplot2 issue talks about your issue.  Hopefully they resolve it for the next release of ggplot2

https://github.com/tidyverse/ggplot2/issues/2464
