### ISSUE TITLE
[Feature Request] Sort ggcoef by estimate size

### ISSUE THREAD

**Issue by alexhallam** [ggobi/ggally#261]
I often find myself in a position where I would like to sort coefficients by the estimate size. I have found that this is possible as described on [this stackoverflow post](https://stackoverflow.com/questions/47189222/sort-by-estimate-size-in-ggcoef). 

It would be a little more user friendly to have a method such as `ggcoeff(sort = TRUE)`  or `ggcoeff(sort = asc/desc)` to automatically sort without having to change the function.

**Comment by schloerke** [comment]
I like it. Can also have `sort = NULL` be the default model ordering.

**Comment by schloerke** [comment]
On cran shortly
