### ISSUE TITLE
Error in make_ggmatrix_plot_obj(wrapp(sub_type, funcArgName = sub_type_name)

### ISSUE THREAD

**Issue by tungmilan** [ggobi/ggally#263]
Hello,

Could you help me with this error? I tried the following code on both Windows and Linux but it didn't work. 

Thanks!

```
Error in make_ggmatrix_plot_obj(wrapp(sub_type, funcArgName = sub_type_name),  : 
  variables: "x" have non standard format: "~d", "~a".  Please rename the columns or make a new column.variables: "colour" have non standard format: "~d", "~a".  Please rename the columns or make a new column.
```

``` r
library(GGally)

df <- structure(list(cli_exp = c(1L, 1L, 2L, 1L, 1L, 0L, 2L, 0L, 1L, 
                1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 1L, 0L, 1L, 2L, 2L, 0L, 1L, 0L, 
                1L, 1L, 2L, 0L, 1L), vcs_exp = c(0L, 0L, 1L, 0L, 0L, 0L, 0L, 
                1L, 0L, 0L, 1L, 1L, 0L, 0L, 1L, 0L, 0L, 1L, 0L, 0L, 1L, 2L, 1L, 
                1L, 0L, 0L, 0L, 2L, 1L, 0L), web_exp = c(2L, 2L, 2L, 1L, 0L, 
                0L, 1L, 2L, 0L, 0L, 3L, 0L, 1L, 0L, 1L, 0L, 1L, 0L, 2L, 1L, 1L, 
                1L, 1L, 0L, 0L, 1L, 1L, 2L, 0L, 0L)), .Names = c("cli_exp", "vcs_exp", 
                "web_exp"), row.names = c(NA, 30L), class = "data.frame")

ggpairs(df, 
    upper = list(continuous = wrap("cor", size = 10)), 
    lower = list(continuous = "smooth"))

#> Error in make_ggmatrix_plot_obj(wrapp(sub_type, funcArgName = sub_type_name), : variables: "x" have non standard format: "~cli_exp".  Please rename the columns or make a new column.

devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.4 (2018-03-15)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  tz       America/Los_Angeles         
#>  date     2018-04-01
#> Packages -----------------------------------------------------------------
#>  package      * version    date       source                            
#>  backports      1.1.2      2017-12-13 CRAN (R 3.4.3)                    
#>  base         * 3.4.4      2018-03-15 local                             
#>  colorspace     1.3-2      2016-12-14 CRAN (R 3.4.4)                    
#>  compiler       3.4.4      2018-03-15 local                             
#>  datasets     * 3.4.4      2018-03-15 local                             
#>  devtools       1.13.5     2018-02-18 CRAN (R 3.4.3)                    
#>  digest         0.6.15     2018-01-28 CRAN (R 3.4.3)                    
#>  evaluate       0.10.1     2017-06-24 CRAN (R 3.4.4)                    
#>  GGally       * 1.3.2      2017-08-02 CRAN (R 3.4.4)                    
#>  ggplot2        2.2.1.9000 2018-03-31 Github (tidyverse/ggplot2@3c9c504)
#>  graphics     * 3.4.4      2018-03-15 local                             
#>  grDevices    * 3.4.4      2018-03-15 local                             
#>  grid           3.4.4      2018-03-15 local                             
#>  gtable         0.2.0      2016-02-26 CRAN (R 3.4.4)                    
#>  htmltools      0.3.6      2017-04-28 CRAN (R 3.4.0)                    
#>  knitr          1.20       2018-03-31 Github (yihui/knitr@03b6e40)      
#>  lazyeval       0.2.1.9000 2018-03-31 Github (hadley/lazyeval@93c455c)  
#>  magrittr       1.5        2014-11-22 CRAN (R 3.4.3)                    
#>  memoise        1.1.0      2017-04-21 CRAN (R 3.4.4)                    
#>  methods      * 3.4.4      2018-03-15 local                             
#>  munsell        0.4.3      2016-02-13 CRAN (R 3.4.3)                    
#>  pillar         1.2.1      2018-02-27 CRAN (R 3.4.3)                    
#>  plyr           1.8.4      2016-06-08 CRAN (R 3.4.4)                    
#>  RColorBrewer   1.1-2      2014-12-07 CRAN (R 3.4.1)                    
#>  Rcpp           0.12.16    2018-03-13 CRAN (R 3.4.4)                    
#>  reshape        0.8.7      2017-08-06 CRAN (R 3.4.4)                    
#>  rlang          0.2.0.9001 2018-03-31 Github (r-lib/rlang@49d7a34)      
#>  rmarkdown      1.9.8      2018-03-31 Github (rstudio/rmarkdown@8cfc878)
#>  rprojroot      1.3-2      2018-01-03 CRAN (R 3.4.3)                    
#>  scales         0.5.0.9000 2018-03-31 Github (hadley/scales@d767915)    
#>  stats        * 3.4.4      2018-03-15 local                             
#>  stringi        1.1.7      2018-03-12 CRAN (R 3.4.3)                    
#>  stringr        1.3.0.9000 2018-03-31 Github (tidyverse/stringr@097c0c0)
#>  tibble         1.4.2      2018-03-31 Github (tidyverse/tibble@5f0b6a0) 
#>  tools          3.4.4      2018-03-15 local                             
#>  utils        * 3.4.4      2018-03-15 local                             
#>  withr          2.1.2      2018-03-31 Github (r-lib/withr@79d7b0d)      
#>  yaml           2.1.18     2018-03-08 CRAN (R 3.4.4)

```

Created on 2018-04-01 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by schloerke** [comment]
Hi @tungmilan,

This is caused from using the GitHub version of ggplot2.  Currently ggally doesn't know how to handle the new `aes` setup.  I'm closing this issue in favor of issue #264.

If you install the cran version of ggplot2, this error should go away.

Thank you!
Barret

**Comment by tungmilan** [comment]
That was my guess as well. Thanks @schloerke !

**Comment by axlehner** [comment]
I have the same issue, but everything comes from CRAN.
Would you have any idea what causes the issue?

`> devtools::session_info()
Session info --------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.383)           
 language en_US                       
 collate  en_US.UTF-8                 
 tz       America/New_York            
 date     2018-04-14                  

Packages ------------------------------------------------------------------------------------------------------------------
 package      * version date       source        
 assertthat     0.2.0   2017-04-11 CRAN (R 3.4.1)
 base         * 3.4.4   2018-03-16 local         
 bindr          0.1     2016-11-13 CRAN (R 3.4.1)
 bindrcpp       0.2     2017-06-17 CRAN (R 3.4.1)
 broom          0.4.3   2017-11-20 CRAN (R 3.4.1)
 cellranger     1.1.0   2016-07-27 CRAN (R 3.4.1)
 cli            1.0.0   2017-11-05 CRAN (R 3.4.1)
 colorspace     1.3-2   2016-12-14 CRAN (R 3.4.1)
 compiler       3.4.4   2018-03-16 local         
 crayon         1.3.4   2017-09-16 CRAN (R 3.4.1)
 datasets     * 3.4.4   2018-03-16 local         
 devtools       1.13.4  2017-11-09 CRAN (R 3.4.1)
 digest         0.6.12  2017-01-27 CRAN (R 3.4.1)
 dplyr        * 0.7.4   2017-09-28 CRAN (R 3.4.1)
 forcats      * 0.2.0   2017-01-23 CRAN (R 3.4.1)
 foreign        0.8-69  2017-06-21 CRAN (R 3.4.0)
 GGally       * 1.3.2   2017-08-02 CRAN (R 3.4.1)
 ggplot2      * 2.2.1   2016-12-30 CRAN (R 3.4.1)
 glue           1.2.0   2017-10-29 CRAN (R 3.4.1)
 graphics     * 3.4.4   2018-03-16 local         
 grDevices    * 3.4.4   2018-03-16 local         
 grid           3.4.4   2018-03-16 local         
 gtable         0.2.0   2016-02-26 CRAN (R 3.4.1)
 haven          1.1.0   2017-07-09 CRAN (R 3.4.1)
 hms            0.4.0   2017-11-23 CRAN (R 3.4.1)
 httr           1.3.1   2017-08-20 CRAN (R 3.4.1)
 jsonlite       1.5     2017-06-01 CRAN (R 3.4.1)
 knitr          1.17    2017-08-10 CRAN (R 3.4.1)
 labeling       0.3     2014-08-23 CRAN (R 3.4.1)
 lattice        0.20-35 2017-03-25 CRAN (R 3.3.3)
 lazyeval       0.2.0   2016-06-12 CRAN (R 3.4.1)
 lubridate      1.7.1   2017-11-03 CRAN (R 3.4.1)
 magrittr       1.5     2014-11-22 CRAN (R 3.4.1)
 memoise        1.1.0   2017-04-21 CRAN (R 3.4.1)
 methods      * 3.4.4   2018-03-16 local         
 mnormt         1.5-5   2016-10-15 CRAN (R 3.4.1)
 modelr         0.1.1   2017-07-24 CRAN (R 3.4.1)
 munsell        0.4.3   2016-02-13 CRAN (R 3.4.1)
 nlme           3.1-131 2017-02-06 CRAN (R 3.4.0)
 parallel       3.4.4   2018-03-16 local         
 pillar         1.0.1   2017-11-27 CRAN (R 3.4.1)
 pkgconfig      2.0.1   2017-03-21 CRAN (R 3.4.1)
 plyr           1.8.4   2016-06-08 CRAN (R 3.4.1)
 prettyunits    1.0.2   2015-07-13 CRAN (R 3.4.1)
 progress       1.1.2   2016-12-14 CRAN (R 3.4.1)
 psych          1.7.8   2017-09-09 CRAN (R 3.4.1)
 purrr        * 0.2.4   2017-10-18 CRAN (R 3.4.1)
 R6             2.2.2   2017-06-17 CRAN (R 3.4.1)
 RColorBrewer   1.1-2   2014-12-07 CRAN (R 3.4.1)
 Rcpp           0.12.12 2017-07-15 CRAN (R 3.4.1)
 readr        * 1.1.1   2017-05-16 CRAN (R 3.4.1)
 readxl         1.0.0   2017-04-18 CRAN (R 3.4.1)
 reshape        0.8.7   2017-08-06 CRAN (R 3.4.1)
 reshape2       1.4.2   2016-10-22 CRAN (R 3.4.1)
 rlang          0.1.6   2017-12-21 CRAN (R 3.4.1)
 rstudioapi     0.7     2017-09-07 CRAN (R 3.4.1)
 rvest          0.3.2   2016-06-17 CRAN (R 3.4.1)
 scales         0.5.0   2017-08-24 CRAN (R 3.4.1)
 stats        * 3.4.4   2018-03-16 local         
 stringi        1.1.5   2017-04-07 CRAN (R 3.4.1)
 stringr      * 1.2.0   2017-02-18 CRAN (R 3.4.1)
 tibble       * 1.4.1   2017-12-25 CRAN (R 3.4.1)
 tidyr        * 0.7.2   2017-10-16 CRAN (R 3.4.1)
 tidyverse    * 1.2.1   2017-11-14 CRAN (R 3.4.1)
 tools          3.4.4   2018-03-16 local         
 utils        * 3.4.4   2018-03-16 local         
 withr          2.1.0   2017-11-01 CRAN (R 3.4.1)
 xml2           1.1.1   2017-01-24 CRAN (R 3.4.1)
 yaml           2.1.14  2016-11-12 CRAN (R 3.4.1)`

**Comment by axlehner** [comment]
In case anyone stumbles across this having the same error, it seems I found a workaround:
`ggpairs(outcomes, lower = list(mapping = aes(color = categorical_variable)))`
just nest the aes environment like this and it works
