### ISSUE TITLE
ggplot2 v2.2.2 compliant

### ISSUE THREAD

**Issue by schloerke** [ggobi/ggally#264]
`aes()` is changing big time in the next version of ggplot2.

Need to fix!!

At least #263 and on gitter

**Comment by cpsievert** [comment]
Here's a more minimal example:

```r
GGally::ggpairs(mtcars)
```

```r
Error in make_ggmatrix_plot_obj(wrapp(sub_type, funcArgName = sub_type_name),  : 
  variables: "x" have non standard format: "~mpg".  Please rename the columns or make a new column.
```

**Comment by bbolker** [comment]
I think this is not going to be too hard; I was able to fix directlabels with [this relatively small pull request](https://github.com/tdhock/directlabels/pull/14) ...

**Comment by schloerke** [comment]
Please install with the code below and let me know how it works for you.
```r
devtools::install_github("ggobi/ggally#266")
```

**Comment by cpsievert** [comment]
yep

**Comment by schloerke** [comment]
on it's way to cran
