### ISSUE TITLE
Adding * for indicate statistical significance on correlation plot

### ISSUE THREAD

**Issue by AndreaQ7** [ggobi/ggally#268]
Goodmorning Everyone,

I'm using function ggpairs to create my correlation plot, but I do not understand how to add * symbol near the coefficient number to indicate if it is significative or not. Does anyone know how help me?
thanks a lot
this is the code i'm running:

`ggpairs(data,mapping=aes(color = Index),upper = list(continuous = wrap('cor', method = "spearman")),lower = list(continuous = 'smooth'))
`

**Comment by schloerke** [comment]
Currently there is no function to display stars for a correlation plot with color.  

If color is not needed, please see the example in https://github.com/ggobi/ggally/issues/139

**Comment by clagiamba** [comment]
Hi,

The function "my_custom_cor" in code in #139
is giving this error: 
Error in is.data.frame(data) : object 'y' not found

Using R version 3.5.0

**Comment by Limor-Raviv** [comment]
Hey @schloerke 
Is there any update on this?
Was hoping to add " * " for significance in my ggpairs correlation matrix as well :)
Cheers!

**Comment by hgoldspiel** [comment]
@schloerke, I'm also interested in adding stars for significance on ggpairs plots with groups distinguished by different colors. Has this been implemented yet?

**Comment by pgrau7** [comment]
Amazing package, thank you! As requested previously, has it been implemented yet? :P It would be really useful!
