### ISSUE TITLE
consistently leaving out all intercept terms when `exclude_intercept = TRUE` in ggcoef

### ISSUE THREAD

**Issue by IndrajeetPatil** [ggobi/ggally#281]
For some `merMod` class objects, the `ggcoef` function removes `intercept` terms when `exclude_intercept = TRUE` from the data frame but still retains the standard deviations from intercept terms. 

Here is an example with `glmer`: 
``` r
library(lme4)
#> Loading required package: Matrix
library(GGally)
#> Loading required package: ggplot2

GGally::ggcoef(
  x =
    lme4::glmer(
      formula = cbind(incidence, size - incidence) ~ period + (1 | herd),
      data = lme4::cbpp,
      family = binomial
    ),
  exclude_intercept = TRUE
)
#> Warning: Removed 1 rows containing missing values (geom_errorbarh).
```

![](https://i.imgur.com/ihyk5Ww.png)

Created on 2018-06-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

As seen here, although the intercept term itself doesn't appear, the sd for intercept does.

In the code, changing the following lines 

https://github.com/ggobi/ggally/blob/caec7a279e444b85cc35b69c43643792a09eaa8c/R/ggcoef.R#L71-L73

to
```
x <- dplyr::filter(.data = x, 
!base::grepl(pattern = "(Intercept)", x = term, ignore.case = TRUE)
)
```

should do the trick.

**Comment by schloerke** [comment]
I think the fix is fair.  Thank you!
