### ISSUE TITLE
displaying only fixed effects for mixed effects models with `ggcoef`

### ISSUE THREAD

**Issue by IndrajeetPatil** [ggobi/ggally#282]
`ggcoef` currently shows both the fixed- and random-effects tems for merMod objects. For example,
``` r
GGally::ggcoef(x = lme4::lmer(
        formula = Reaction ~ Days + (Days | Subject),
        data = lme4::sleepstudy
      ), effects = "fixed", group = "fixed", exclude_intercept = TRUE)
#> Warning: Ignoring unknown parameters: effects
#> Warning: Removed 4 rows containing missing values (geom_errorbarh).
```

![](https://i.imgur.com/QPj1n3d.png)

Created on 2018-06-14 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

It will be good to have option to just show the fixed effects since this is what most people are interested in. 

https://github.com/ggobi/ggally/blob/caec7a279e444b85cc35b69c43643792a09eaa8c/R/ggcoef.R#L56-L64

Here, you can add few more arguments that will come in handy for `merMod` objects:

```
if (!is.data.frame(x)) { 
   require_namespaces("broom") 
   x <- broom::tidy( 
     x, 
     conf.int = conf.int, 
     conf.level = conf.level, 
     exponentiate = exponentiate,
     effects = "fixed",                       # this can be a new argument
     group = "fixed"                         # this can be a new argument
   ) 
 } 
```

**Comment by schloerke** [comment]
I don't think I'll add the parameters for all broom::tidy evaluations.  I also don't like to add something for  special circumstances without handling all regular circumstances first.  

What about adding an extra `broomArgs = list()` parameter or add s3 method (like `ggcoef_data(x, ...)` for cleaning ggcoef data.  Then anyone could add their own s3 method for new data types.  With the function, it could be used as 
```r
mod = lme4::lmer(
  formula = Reaction ~ Days + (Days | Subject),
  data = lme4::sleepstudy
)

GGally::ggcoef(
  x = GGally::ggcoef_data(mod, effects = "fixed", group = "fixed"), 
  exclude_intercept = TRUE
)


### .... or.....

GGally::ggcoef(
  x = mod,
  broomArgs = list(effects = "fixed", group = "fixed"),
  exlucde_intercept = TRUE
)
```


With the arguments of `conf.int`, `conf.level`, and `exponentiate` being exposed in the function, I'm leaning towards using `broomArgs = list()`.  Thoughts?

**Comment by IndrajeetPatil** [comment]
That works as well!!

**Comment by schloerke** [comment]
`broomArgs = list()` it is, then

**Comment by IndrajeetPatil** [comment]
@schloerke Thanks for quickly resolving this. I currently have a new function in development for my package that relies on `ggcoef` and that's why I need these new features (https://indrajeetpatil.github.io/ggstatsplot/reference/ggcoefstats.html). 

Lemme know when they are either in development or main branch and I will give it a spin!

**Comment by briatte** [comment]
Looks like this issue has been solved :)
