### ISSUE TITLE
ggsurv gives nonsense legend with multiple factors

### ISSUE THREAD

**Issue by EdwinTh** [ggobi/ggally#283]
HT to Michael by email:

Training a CoxPH model on multiple factors gives a plot with nonsensical legend. The plot seems to turn out fine, but the legend should be meaningful.

```r
l <- survival::lung %>% dplyr::mutate(age_cat = as.factor(age > 60))
lung.surv2 <- survival::survfit(Surv(time,status) ~ sex+age_cat, data = l)
ggsurv(lung.surv2)
```

**Comment by smouksassi** [comment]
you might want to try geom_km from ggquickeda (disclaimer package maintainer)
you build your survival model formula in the geom aesthetics 
````r
 ggplot(l)+
   ggquickeda::geom_km(aes(time=time,status=status,color=interaction(sex,age_cat)))
````

**Comment by schloerke** [comment]
Hi Samer! Long time no see! 

Very true! I will have to copy how your interaction is in the label of the legend.  I still appreciate how `ggsurv` orders the legend though.  (Ranked from top to bottom by ending survival value)

For records...

Bad image:
![screen shot 2018-08-16 at 10 25 23 am](https://user-images.githubusercontent.com/93231/44214709-c29e5200-a13e-11e8-98b2-1e063c7efbd5.png)

geom_km:
![screen shot 2018-08-16 at 10 28 37 am](https://user-images.githubusercontent.com/93231/44214901-2c1e6080-a13f-11e8-8e99-fad52bceeaf1.png)

**Comment by smouksassi** [comment]
Hi Barret,
very nice hearing from you indeed ! Awesome flexible package that I rely on very often. It is a nice touch to order the legend in the same order as the K-M curves end so we can quickly find who is who.
Unrelated but I could not comment on the other closed issue. I found the rlang::eval_tidy a good replacement code for evaluating mappings that are now quosures instead for eval that does not work.
