### ISSUE TITLE
How do provide we title for the chart?

### ISSUE THREAD

**Issue by mathan4stat** [ggobi/ggally#285]
How do we add a title for the chart in the following code? 
`ggscatmat(df, columns = 1: ncol(df1))`

I am using this code to create charts for many factors, hence it is important to add chart title for the same.

**Comment by schloerke** [comment]
ggscatmat returns a full ggplot2 object. Please add a title using labs().

ggscatmat(df, columns = 1: ncol(df1)) + labs(title = “ my title”)

- Barret
