### ISSUE TITLE
warning with R 3.6.0

### ISSUE THREAD

**Issue by IndrajeetPatil** [ggobi/ggally#292]
The development version of `R` produces the following warning message after loading `ggally`
```r
Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2
```

**Comment by SimeoneMarsico** [comment]
Did you understand if in the end that is a problem or causes any bug? Thanks, Giovanni

**Comment by schloerke** [comment]
It should be fine.

This should be fixed in the next version.  I welcome a PR as well!

**Comment by schloerke** [comment]
Trying to address the warning here: https://github.com/tidyverse/ggplot2/pull/3815 . 

From my current understanding, it'll need an update within `ggplot2`.
