### ISSUE TITLE
Error in unit(...) with example 

### ISSUE THREAD

**Issue by mo-seph** [ggobi/ggally#3]
When I try to run the example code, I get the following error:

```
> ggpairs(iris[,3:5])
[1] "box"
[1] FALSE
Error in unit(x, default.units) : 'x' and 'units' must have length > 0
```

EDIT: when I run this, it draws the top row ("Petal.Length", Corr: 0.963, a box plot) and the first panel of the second row - a scatterplot.

It works OK with ggpairs(iris[,1:3]), however

I'm using ggplot2_0.9.1 and GGally_0.3.2

**Comment by gokceneraslan** [comment]
With the latest ggally installed from git, I am getting a similar error 

```
Error in unit(tic_pos.c, "mm") : 'x' and 'units' must have length > 0
```

 when I try the following code:

```
ggpairs(iris[,3:5], color='Petal.Width')
```
