### ISSUE TITLE
columnLabels text size

### ISSUE THREAD

**Issue by edvbb** [ggobi/ggally#303]
Sorry, just a simple question. How to change columnLabels text size.
I can use 
`    
  theme(axis.text.x = element_text(size = 12),`
for the axis text but it does not work for columnLabels

**Comment by schloerke** [comment]
Look at using the ggplot2 theme option `strip.text` (And `strip.text.x` and `strip.text.y`). 

Let me know how it goes. Thank you!

**Comment by edvbb** [comment]
Thanks, it works 
`theme(strip.text = element_text(size = 25))`
