### ISSUE TITLE
Strange ggpairs behaviour

### ISSUE THREAD

**Issue by iago-pssjd** [ggobi/ggally#306]
I was looking on Internet how to do a `pairs` plot à la `ggplot` and the main suggestion I found was using `GGally::ggpairs`, so I tried. 

While the output of using `pairs` as follows
```
library(dplyr)
SW <- starwars %>% 
  select(height:species) %>% 
  mutate(hair_color = as.factor(hair_color), 
         skin_color = as.factor(skin_color), 
         eye_color = as.factor(eye_color), 
         gender = as.factor(gender), 
         homeworld = as.factor(homeworld), 
         species = as.factor(species))
pairs(SW)
```
is:
![pairs](https://user-images.githubusercontent.com/40892925/70376871-2fc68f80-190e-11ea-83c3-60f2dd704afb.png)
The output of using `GGally::ggpairs` is:
```
> library(GGally)
> ggpairs(SW)
Error in stop_if_high_cardinality(data, columns, cardinality_threshold) : 
  Column 'skin_color' has more levels (31) than the threshold (15) allowed.
Please remove the column or increase the 'cardinality_threshold' parameter. Increasing the cardinality_threshold may produce long processing times
> ggpairs(SW, cardinality_threshold = 50)
```
![ggpairs](https://user-images.githubusercontent.com/40892925/70376930-921f9000-190e-11ea-8b21-8653c7cf7093.png)
which does not seem a reasonable expected output.

**Comment by schloerke** [comment]
So `pairs` does an alteration to the data and turns everything into numeric data.  

If we do the same...

```r
SW %>%
  mutate_all(as.numeric) %>%
  ggpairs()
```
<img width="1173" alt="Screen Shot 2020-02-09 at 9 00 20 PM" src="https://user-images.githubusercontent.com/93231/74115914-46dc6480-4b7f-11ea-8dcf-c2f96707a32b.png">

... we get a very similar plot to the one created by pairs.  

`ggpairs` is trying to maintain the factor information that was original given by data.  This caused some of the plots to try to print too much in such a small space. 

I do not believe this is a bug... just an unfortunate side effect of printing a plot with too many facets in a small area.  I believe if the plot of enlarged to 50" square, you would be able to see each plot and all of its complexity.

Hope this solves your issue!

**Comment by iago-pssjd** [comment]
Thanks! Now I understand.
