### ISSUE TITLE
Can't install GGally from CRAN 

### ISSUE THREAD

**Issue by Maxi1162** [ggobi/ggally#314]
While Installing GGally, the below error comes, kindly help

> install.packages("GGally")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/Prashant Gupta/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.6:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.6/PACKAGES'

  There is a binary version available but the source version is later:
       binary source needs_compilation
GGally  1.4.0  1.5.0             FALSE

installing the source package ‘GGally’

trying URL 'https://cran.rstudio.com/src/contrib/GGally_1.5.0.tar.gz'
Content type 'application/x-gzip' length 1053211 bytes (1.0 MB)
downloaded 1.0 MB

* installing *source* package 'GGally' ...
** package 'GGally' successfully unpacked and MD5 sums checked
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: package or namespace load failed for 'ggplot2':
 .onLoad failed in loadNamespace() for 'pillar', details:
  call: utils::packageVersion("vctrs")
  error: there is no package called 'vctrs'
Error: package 'ggplot2' could not be loaded
In addition: Warning message:
package 'ggplot2' was built under R version 3.6.3 
Execution halted
ERROR: lazy loading failed for package 'GGally'
* removing 'C:/Users/Prashant Gupta/Documents/R/win-library/3.6/GGally'
Warning in install.packages :
  installation of package ‘GGally’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\Prashant Gupta\AppData\Local\Temp\RtmpcdxBZE\downloaded_packages’

**Comment by schloerke** [comment]
Binaries should be built within a couple days. Closing for now. Please reopen this if it is still a problem after April 2nd

**Comment by Martaw-code** [comment]
At 2025/01/11 -> Try updating R to version 4.4.2 by downloading the package from: https://cran.r-project.org/bin/macosx/

And then try to install again the package from CRAN:

install.packages("GGally"

This will solve also the problem installing ggstats
