### ISSUE TITLE
Generalize ggally_cor

### ISSUE THREAD

**Issue by schloerke** [ggobi/ggally#318]
This function should take in a `fn` that returns the text.  The general function should handle the complete cases and color splitting.

The `ggally_cor`'s  `fn` will need to:
* assert numeric
* perform cor using `method`
* trim to signif digits (better if fixed number of digits)
* Return text

**Comment by larmarange** [comment]
It would allow to easily implement https://github.com/ggobi/ggally/issues/286

**Comment by schloerke** [comment]
Fixed in https://github.com/ggobi/ggally/pull/327
