### ISSUE TITLE
lowertriangle() could be faster with memory preallocation

### ISSUE THREAD

**Issue by vlepori** [ggobi/ggally#322]
I was tinkering with the package functions (needed a matrix scatterplot with continuous variable color aesthetic) and saw that `lowertriangle()` generates the expanded dataframes for plots by [growing a df inside a nested loop](https://github.com/ggobi/ggally/blob/242f426d836dc579f99d2305479903ee2e71a469/R/ggscatmat.R#L29).
This seems inefficient and unnecessary, since we know the final dimension of the output. So I made a version of the function with memory preallocation, and it is notably faster with larger data.
![image](https://user-images.githubusercontent.com/42210264/80714235-e95c1200-8af4-11ea-8999-4467e05f811b.png)
The actual plotting might still take the most time, but if there is interest I'd be happy to share the code or make a PR. Thanks for the nice package!

**Comment by schloerke** [comment]
oh goodness. Good find @vlepori !  A PR is always welcome!

**Comment by schloerke** [comment]
Fixed in #328
