### ISSUE TITLE
Vignette of Awesomeness by Joseph Lamar

### ISSUE THREAD

**Issue by schloerke** [ggobi/ggally#334]
@larmarange You are adding a LOT of very good additions.  

I would like to include vignette(s) of the new methods.  

I don't mind having this vignette on a patch release to give it proper time/attention. But I believe it should be done in some form to highlight what you've added to `GGally`

**Comment by schloerke** [comment]
The vignettes will be hosted using `pkgdown`.  It's on my short list of things to do. https://github.com/ggobi/ggally/issues/307

**Comment by larmarange** [comment]
Yes, vignettes have to be written!! ;-)
It's on my TO DO list
