### ISSUE TITLE
Namespace clash with `ggpubr`

### ISSUE THREAD

**Issue by schloerke** [ggobi/ggally#370]
cc @larmarange 

Both packages produce `median_iqr` and `mean_sd`.  This is causing a namespace clash with `robustSingleCell`. See https://github.com/asmagen/robustSingleCell/pull/34

Is there another name we can use? If we have a different name, we can resubmit now (and include your fix). Otherwise, we will most likely have to wait two weeks.

**Comment by larmarange** [comment]
No, the best would be to change names. 

An option could be `median_iqr_summary` and `mean_sd_summary` ?

**Comment by larmarange** [comment]
Or would you prefer `weighted_median_iqr` and `weighted_mean_sd`? These two names seem unused so far in R package (according to rdocumentation website). It highlights that both function have a weight parameter.

**Comment by schloerke** [comment]
I'm a fan of `weighted_*()`!

**Comment by schloerke** [comment]
Do you mind making a PR? I'll incorporate that and #369 and send to CRAN

**Comment by larmarange** [comment]
PR done
