### ISSUE TITLE
Redesigning ggcoef()

### ISSUE THREAD

**Issue by larmarange** [ggobi/ggally#372]
I'm just opening the discussion some possible evolutions of `ggcoef()`.

I have the feeling that a lot of improvements are possible, in particular:

- a better default theme
- adding variable names on the plot and taking into account existing variable labels 
- adding reference values for categorical variables
- easily visualising significant coefficients
- easy comparison of models

Here an example of the current version of `ggcoef()`

```r
d <- as.data.frame(Titanic)
log.reg <- glm(Survived ~ Sex + Age + Class, family = binomial, data = d, weights = d$Freq)
ggcoef(log.reg, exponentiate = TRUE)
```

![image](https://user-images.githubusercontent.com/966307/83946467-62940680-a811-11ea-98c8-906f32015be0.png)

I started to explore a new version, called for now `ggcoef_model()` taking advantages of `gtsummary::tbl_regression()` for pre-processing the data.

The new experimental functions are available in https://github.com/larmarange/JLutils/ allowing to test them.

```r
ggcoef_model(log.reg, exponentiate = TRUE)
```

![image](https://user-images.githubusercontent.com/966307/83946520-adae1980-a811-11ea-8bb3-b2d1909df7a1.png)

I have also added a `ggcoef_compare()` for comparing several models.

```r
log.reg2 <- glm(Survived ~ Sex * Age + Class, family = binomial, data = d, weights = d$Freq)
ggcoef_compare(list(first = log.reg, "with interaction" = log.reg2))
```

![image](https://user-images.githubusercontent.com/966307/83946571-02519480-a812-11ea-884c-4ed691c74043.png)

```r
ggcoef_compare(list(first = log.reg, "with interaction" = log.reg2), type = "faceted")
```

![image](https://user-images.githubusercontent.com/966307/83946588-185f5500-a812-11ea-9aad-d8b626e46679.png)

**Comment by larmarange** [comment]
I would appreciate some feedback about the redesign of `ggcoef`.

So far, I have adopted different names, so the new `ggcoef_*()` functions could come in addition to the historical one.

Note that there is a `ggcoef_multinom()` for this specific case, but it requires for now the dev version of `gtsumarry`.

The main idea is to pre-test all these functions in `JLutils` before moving them to `GGally` once mature enough.

**Comment by larmarange** [comment]
Source code is visible here https://github.com/larmarange/JLutils/blob/master/R/ggcoef_model.R

Note that I have also added a new geom `geom_stripped_rows()`

**Comment by schloerke** [comment]
Very exciting! I am a big fan of `ggcoef_compare`.  We'll have a whole suit of model comparison methods.

------------------

Notes:

* I am wondering if we can use `signif_stars` on the labels of the groups. The data does not need to change, but we can change the label.  I find the `p value` (hole / not hole) too many places to look.  I can scan the labels quickly on the left side and the name / significance is right next to each other.

* I don't know if it's on purpose, but the `with interaction` and `Sex * Age` is a "dark row". Looking at it, I would have guessed it to be a "light row".

* Could we could make the `0` line a form of dark grey. The dark line matches the "data" line and is distracting. Like your dashed lines, it should be findable when needed.

* It'll be a challenge, but can `ggcoef_compare` maintain model position even if the other model does not have that coefficient? I think this could be done by adding `NA` data for coefs that doesn't exist (but an actual color value).  This way if I see a line in the middle row, I know it's from the middle group. Ex: If the "red group" (3rd group) happens to be only model with a particular coef, ("blue" and "green" do not exist), then the red line will always be displayed in the 3rd slot within the row even if the first two slots are empty.

* `ggcoef_multinom` is very neat! Because of the high chance of missing combinations, would this be better to be done by wrapping around `ggduo` and using the `*Proportions`? ... I guess this would also apply to the other `ggcoef_*()` methods. This would also help alleviate the double labels on the left.  The missing combinations could be displayed as a `"blank"` plot
	* By switching to wrapping around `ggduo`, `geom_stripped_rows` might naturally fix itself

**Comment by larmarange** [comment]
Thank you for your feedback.

Some comments bellow.

> * I am wondering if we can use `signif_stars` on the labels of the groups. The data does not need to change, but we can change the label.  I find the `p value` (hole / not hole) too many places to look.  I can scan the labels quickly on the left side and the name / significance is right next to each other.

It is easy to implement but relevant only when plotting one model (i.e. for `ggcoef_model()`) but not for `ggcoef_compare()` or `ggcoef_multinom()` (because there are several p-value for the same modality).

I just added a quick implementation of it, simply adding the stars after the name of the modality. Maybe could be improved, for example could be more easy to read if significant stars are in brakets. Similarly, should we provide an option to indicate directly the p-value in the labels?

> * I don't know if it's on purpose, but the `with interaction` and `Sex * Age` is a "dark row". Looking at it, I would have guessed it to be a "light row".

Due to the fact that the plot is facetted by variable name with `space = free_y`, `geom_stripped_rows()` is computed separately for each facet, so the lower row in a facet is always dark. 

We would need to find a trick to indicate to `geom_stripped_rows()` if the first row should be odd or even. Not sure how to do it.

> * Could we could make the `0` line a form of dark grey. The dark line matches the "data" line and is distracting. Like your dashed lines, it should be findable when needed.

I have added a vline_colour option and changed default value for grey50.

> * It'll be a challenge, but can `ggcoef_compare` maintain model position even if the other model does not have that coefficient? I think this could be done by adding `NA` data for coefs that doesn't exist (but an actual color value).  This way if I see a line in the middle row, I know it's from the middle group. Ex: If the "red group" (3rd group) happens to be only model with a particular coef, ("blue" and "green" do not exist), then the red line will always be displayed in the 3rd slot within the row even if the first two slots are empty.

I have added some code in `ggcoef_compare()` to generate rows with NA values for unobserved terms in a model. It allows to preserve vertical positioning and also allows to compute the stripped rows in such case.

![image](https://user-images.githubusercontent.com/966307/84047074-2e544d80-a9ab-11ea-98fc-1e535308f286.png)

![image](https://user-images.githubusercontent.com/966307/84047112-37451f00-a9ab-11ea-9b75-ec7f4fed5c38.png)


> * `ggcoef_multinom` is very neat! Because of the high chance of missing combinations, would this be better to be done by wrapping around `ggduo` and using the `*Proportions`? ... I guess this would also apply to the other `ggcoef_*()` methods. This would also help alleviate the double labels on the left.  The missing combinations could be displayed as a `"blank"` plot
>   
>   * By switching to wrapping around `ggduo`, `geom_stripped_rows` might naturally fix itself

I'm truly sorry but I did not understand your point here.

Which missing combinations are you referring to?

In addition, I do not see how to wrap `ggcoef_()` with `ggduo()`? `ggduo()` is designed when comparing separate columns together which is simply not the way data are organized in `ggcoef_()`

**Comment by larmarange** [comment]
> * I don't know if it's on purpose, but the `with interaction` and `Sex * Age` is a "dark row". Looking at it, I would have guessed it to be a "light row".

I found a solution. Should be OK now.

**Comment by jeffbone** [comment]
Hi There,

Love the package and the function for model visualization! 

Is it possible to add an option to remove the p-values from ggcoef_compare? 

Some of your other functions have a `show_p_values` option,which I find handy as I prefer not to dichotomize my p-values into above and below some value. 

Cheers,
Jeff

**Comment by larmarange** [comment]
` ggcoef_compare(models, significance = NULL)` ?

![image](https://user-images.githubusercontent.com/966307/149131145-a1bfc619-6149-4a2c-b44e-cb4fc74c266d.png)

**Comment by larmarange** [comment]
`show_p_values` determines if p-value are displayed in labels (not possible for compare)
`significance` determines if points are drawn differently according to p-value

**Comment by jeffbone** [comment]
Ah, I must have missed that. Appreciate the quick reply. 

Thanks,
Jeff

**Comment by rn26** [comment]
Hi. I'm trying to install the package broom.helpers - https://rdocumentation.org/packages/broom.helpers/versions/1.6.0.  But my R doesn't recognize the package, and I cannot use ggcoef_model(). Is this a common issue people encounter?  Do you have a suggestion as to how I may be able to use the package? Thanks!

**Comment by larmarange** [comment]
This is strange. `broom.helpers` is available on CRAN : https://cran.r-project.org/web/packages/broom.helpers/index.html

Which version of R are you using?

**Comment by rn26** [comment]
I realized I hadn't upgraded R in a while. And the problem was solved after I installed the latest version of R. Thanks for your prompt response!
