### ISSUE TITLE
font problems under Linux, if TeX is installed

### ISSUE THREAD

**Issue by lindemann09** [ggobi/ggally#373]
Fonts are scrambled under Debian Linux (Ubuntu 20.04), if latex is installed (`texlive-fonts-recommended`).

**Workaround**: Uninstalling `texlive-fonts-recommended` temporally 

```r
library(GGally)
ggpairs(mtcars[, c('mpg', 'cyl')])
```

![screenshot](https://raw.githubusercontent.com/lindemann09/cogpsy.eu/master/img/ggplot_bug.png)

**Comment by lindemann09** [comment]
same issue as https://github.com/tidyverse/ggplot2/issues/4055

**Comment by jolars** [comment]
Wouldn't it make sense to avoid the monospace fonts altogether in ggally?
