### ISSUE TITLE
ggpairs: show axis line for evreyplots?

### ISSUE THREAD

**Issue by lizhaozhi** [ggobi/ggally#388]
Hi,
I am trying to make a plot with ggpairs(). But I need to show the axis for every subplot. any idea?
Thank you

**Comment by schloerke** [comment]
Hi @lizhaozhi 

I'd recommend using [`patchwork`](https://patchwork.data-imaginist.com/).  `patchwork` does a GREAT job aligning axis values and combining plots.

Note: You can retrieve plots from your GGally plot matrix using `pm[i,j]` and then use `patchwork` to combine the plots... 

``` r
library(ggplot2)
library(GGally)
#> Warning: package 'GGally' was built under R version 4.0.2
#> Registered S3 method overwritten by 'GGally':
#>   method from   
#>   +.gg   ggplot2
library(patchwork)
#> Warning: package 'patchwork' was built under R version 4.0.2
pm <- ggpairs(iris, 1:3)
pm
```

![](https://i.imgur.com/My69MD6.png)

``` r

# manually
pm_mpatch <-              pm[1,1] + pm[1,2] + pm[1,3]
pm_mpatch <- pm_mpatch / (pm[2,1] + pm[2,2] + pm[2,3])
pm_mpatch <- pm_mpatch / (pm[3,1] + pm[3,2] + pm[3,3])
pm_mpatch
```

![](https://i.imgur.com/CpPBglM.png)

``` r


# general solution (any ggmatrix object)
pm_patch <- NULL
for (i in seq_len(pm$nrow)) {
  patch_row <- NULL
  for (j in seq_len(pm$ncol)) {
    patch_row <- 
      if (j == 1) {
        pm[i,j]
      } else {
        patch_row + pm[i,j]
      }
  }
  if (i == 1) {
    pm_patch <- patch_row
  } else {
    pm_patch <- pm_patch / patch_row
  }
}
pm_patch
```

![](https://i.imgur.com/zVUpeli.png)

<sup>Created on 2020-09-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
