### ISSUE TITLE
Allowing rmarkdown in Roxygen

### ISSUE THREAD

**Issue by larmarange** [ggobi/ggally#390]
Would you consider to change `Roxygen: list(markdown = FALSE)` by `Roxygen: list(markdown = TRUE)` in DESCRIPTION?

It would be much easier to write documentation and ensure that internal and external links are accurate with the last versions of R. (cf. https://github.com/r-lib/roxygen2/issues/1108 )

**Comment by schloerke** [comment]
Yes! Thank you!
