### ISSUE TITLE
`stat_cross()` and `ggtable()` broken since `broom` v7.0.0

### ISSUE THREAD

**Issue by larmarange** [ggobi/ggally#391]
In version 7.0.0, `broom` has changed column names of the tibble produced by `augment.htest()`.

As a result, `ggatable()` produce an error when displaying residuals.

**Comment by larmarange** [comment]
A fix has been proposed and added to PR #375

**Comment by larmarange** [comment]
As it's breaking current stable version of GGally, it could be worth to consider releasing a version 2.0.1.

**Comment by larmarange** [comment]
Dear @schloerke 

would you consider releasing a new version of GGally?

**Comment by schloerke** [comment]
Yes! GitHub Actions has really helped a lot. 

I've started a `rc-v2.1.0` branch (https://github.com/ggobi/ggally/pull/397) and updated the DESCRIPTION version. Do you mind making a PR with an updated news entry for #392 ?  I'll run revdep and CRAN windows checks afterwards.

...then we should be good to go!

**Comment by larmarange** [comment]
PR done, cf #398 

Thanks and best regards
