### ISSUE TITLE
ggpairs correlation plot shouldn't show p-values

### ISSUE THREAD

**Issue by schmettow** [ggobi/ggally#393]
Using ggpairs on a set of metric variables produces correlation coefficients in the upper triangle. Since a recent update, this also prints p-values. P-values only make sense under the frequentist null hypothesis testing paradigm. I believe that, by default, exploratory plots should be paradigm-free. Especially, for everyone doing Bayesian Statistics, this command has become useless.

**Comment by schloerke** [comment]
Duplicate of https://github.com/ggobi/ggally/issues/377
