### ISSUE TITLE
Feature Request: allow stat_prop() to work with a y aesthetic

### ISSUE THREAD

**Issue by smouksassi** [ggobi/ggally#395]
Thank you for the amazing extra functionality and the great package and the recent extra stats that open new possibilities in ggplot2. Would it make sense to allow stat_prop to work with a y aesthetic and no x similarly to how geom_barplot now works with auto flipping?

``` r
  library(ggplot2)
  library(GGally)
#> Registered S3 method overwritten by 'GGally':
#>   method from   
#>   +.gg   ggplot2
  ggplot(mtcars,aes(x=cut_interval(mpg,n=3),
                    fill =as.factor(cyl), color =as.factor(cyl)
                               )) +
    geom_bar(alpha=0.2,position =  position_fill(vjust = 0.5)) +
    geom_text(stat = "prop",aes(by = cut_interval(mpg,n=3)),
              position =  position_fill(vjust = 0.5)) 
```

![](https://i.imgur.com/gphwwWz.png)

``` r
  
  p<- ggplot(mtcars,aes(y=cut_interval(mpg,n=3),
                    fill =as.factor(cyl), color =as.factor(cyl)
  )) +
    geom_bar(alpha=0.2,position =  position_fill(vjust = 0.5))
  p
```

![](https://i.imgur.com/wJL1a9d.png)

``` r
  p +
    geom_text(stat = "prop",aes(by = cut_interval(mpg,n=3)),
              position =  position_fill(vjust = 0.5)) 
#> Error: stat_prop() must not be used with a y aesthetic.
```
<sup>Created on 2020-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
---

**Comment by larmarange** [comment]
The easy solution for horizontal bar plots is to use `coord_flip()`.

**Comment by larmarange** [comment]
OK, after exploration, the possibility to allow x or y has been introduced in `ggplot 3.3.0`.

I could check the code of stat_prop to allow it.

**Comment by larmarange** [comment]
#396 should fix it

``` r
library(ggplot2)
library(GGally)
#> Registered S3 method overwritten by 'GGally':
#>   method from   
#>   +.gg   ggplot2

ggplot(mtcars) +
  aes(
    y = cut_interval(mpg,n=3),
    fill = as.factor(cyl), 
    color =as.factor(cyl)
  ) +
  geom_bar(alpha=0.2, position =  position_fill(vjust = 0.5)) +
  geom_text(stat = "prop", aes(by = cut_interval(mpg,n=3)),
            position =  position_fill(vjust = 0.5)) 
```

![](https://i.imgur.com/IRhuSeK.png)

<sup>Created on 2020-12-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by smouksassi** [comment]
This was amazingly fast. Indeed the request about consistency and between ggplot auto x/y stats and GGally thank you much.
