### ISSUE TITLE
ggscatmat plot layout with 10 or more columns

### ISSUE THREAD

**Issue by marioniepel** [ggobi/ggally#399]
When generating basic plots with ggscatmat the layout of the plot layouts is faulty when a larger number of columns is selected in the same dataset (17 data columns with about 50 observations).  I was trying to figure out if there is a specified limit to the number of columns that can be processed in the help file `?ggscatmat` but did not see an restriction on column number.

7 columns:
![small](https://user-images.githubusercontent.com/5176275/105386775-cc1b2680-5be2-11eb-89f7-8fa0c32e8b75.png)

10 columns
![medium](https://user-images.githubusercontent.com/5176275/105386778-cd4c5380-5be2-11eb-9234-05968f6c9d25.png)

17 columns
![large](https://user-images.githubusercontent.com/5176275/105386780-ce7d8080-5be2-11eb-9f4e-73afd91b4f3f.png)

**Comment by schloerke** [comment]
Answered in https://community.rstudio.com/t/ggscatmat-plots-in-ggally-not-working-with-increasing-col-numbers/94512/2?u=barret

> Use `ggpairs()`
