### ISSUE TITLE
ggally overwrites the ggplot2 `+` method

### ISSUE THREAD

**Issue by AHoerner** [ggobi/ggally#410]
Hi! Um, do you actually intend to overwrite the `+` method of ggplot2? If so, do you have some reason to believe that ggplot will function correctly with a different + method?

On loading ggally, I get this warning:
Registered S3 method overwritten by 'GGally':
  method from   
  +.gg   ggplot2

Andrew

**Comment by schloerke** [comment]
Yes.  This is what allows `GGally` to do things like 

```r
pm <- ggpairs(iris)
# calls GGally.`+` which will internally call ggplot2.`+`
pm + theme_bw()
```

Related: https://github.com/ggobi/ggally/issues/292

**Comment by schloerke** [comment]
Yes. If the left side is not a plot matrix object, `` GGally.`+` `` will pass it through to `` ggplot2.`+` ``

Going to close as `GGally` can not fix the underlying issue.

**Comment by dmi3kno** [comment]
Related to #416
