### ISSUE TITLE
Proposal to make `stat_n_text` usable without y aesthetic by supplying y.pos directly

### ISSUE THREAD

**Issue by danielinteractive** [ggobi/ggally#423]
Hello,

first of all thanks a lot for the nice package!

Recently we wanted to use `stat_n_text` also for barplots, where there is no y aesthetic. So we found a way to supply the y.pos directly in that case.
Would that be of interest? Then I can provide a PR.

Thanks,
cheers
Daniel

**Comment by danielinteractive** [comment]
Hi @schloerke, do you have any feedback on this?

**Comment by schloerke** [comment]
Hi @danielinteractive !

I've been offline, sorry for the delay. 

I see `stat_n_text()` as a part of {EnvStats}: https://www.rdocumentation.org/packages/EnvStats/versions/2.3.1/topics/stat_n_text . 

Do you mind making a PR to start the conversation? Thank you

**Comment by danielinteractive** [comment]
Thanks @schloerke - oops then I confused the packages here :-D 
Closing here and opening in EnvStats then... thanks!
