### ISSUE TITLE
Threre is no simple way to add settings such as alpha= to all plots without it appearing in the legend.

### ISSUE THREAD

**Issue by krivit** [ggobi/ggally#439]
I encountered this when I set out to make a pairwise plot matrix with several quantitative variables a single categorical variable, which I wanted to use to colour-code the scatter plots and the density plots with transparency.

For example,
``` r
library(GGally)
data(iris)
ggpairs(iris,
  aes(colour=Species, alpha=0.3), # Colour-code Species, use transparency.
  legend=1) # Grab legend from the first plot.
```

![](https://i.imgur.com/NcBOXAL.png)

<sup>Created on 2022-06-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

However,  this renders a legend for `alpha` as well. As far as I know, this can be fixed in one of two ways:
1. By passing `alpha` to the specific `geom_*()` directly rather than through the mapping.
2. By adding `+ guides(alpha="none")`.

The first approach requires rewriting the `upper=`, `lower=`, and `diag=` arguments, and the second approach produces the following error:
``` r
library(GGally)
#> Loading required package: ggplot2
#> Registered S3 method overwritten by 'GGally':
#>   method from   
#>   +.gg   ggplot2
data(iris)
ggpairs(iris,
  aes(colour=Species, alpha=0.3), # Colour-code species, use transparency.
  legend=1) + guides(alpha="none") # Grab legend from the first plot, removing guide for alpha.
#> Error in `+.gg`(e1, item): 'ggmatrix' does not know how to add objects that do not have class 'theme', 'labels' or 'ggproto'. Received object with class: 'character'
```
<sup>Created on 2022-06-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

It would be helpful to either implement some way to pass a global argument to all plots or add support for adding `guides` to a `ggmatrix`.

**Comment by schloerke** [comment]
I don't believe the `alpha` was actually supplied as `0.3` exactly. ... But more like a group name of `0.3`.

Adding a `I()` around the `0.3` to make `alpha = I(0.3)` tells `{ggplot2}` to use the value "AsIs". 

Updated code and output:
```r
library(GGally)
data(iris)
ggpairs(iris,
  aes(colour=Species, alpha=I(0.3)),
  legend=1
)
```

<img width="833" alt="Screen Shot 2022-06-06 at 11 54 17 AM" src="https://user-images.githubusercontent.com/93231/172197853-bb47889f-9a03-4103-ad4f-0613658c7919.png">


... But that applies the alpha to everything which may not be what you want.
