### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [ggobi/ggally#451]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that this is due to changes in the warnings and errors thrown by ggplot2 that you test for in your package

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by larmarange** [comment]
Dear @thomasp85 

I'm trying to explore some of the warnings raised by the new version of `ggplot2`. I have a quick question regarding the `weight` aesthetic.

The following code is producing a warning (it was not the case before).

``` r
ggplot(as.data.frame(Titanic)) + 
  aes(x = Age, fill = Survived, weight = Freq) + 
  geom_bar(position = "fill")
#> Error in ggplot(as.data.frame(Titanic)): impossible de trouver la fonction "ggplot"
```

<sup>Created on 2022-10-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Do you know why? What would be the correct syntax?

**Comment by thomasp85** [comment]
Thanks for getting back to me on this. That is indeed an issue in ggplot2 and will be fixed so you can disregard that warning

**Comment by larmarange** [comment]
Thank @thomasp85 for your quick feedback. Do you have the issue number, so I could subscribe to it.
It seems that most of the warnings are coming from it.

**Comment by thomasp85** [comment]
No, this will be fixed directly in the release candidate - you can reinstall that and test with the fix applied

**Comment by larmarange** [comment]
OK thanks
