### ISSUE TITLE
Make `{ggstats}` package and reexport within `{GGally}`

### ISSUE THREAD

**Issue by schloerke** [ggobi/ggally#452]
_Originally posted by @schloerke in https://github.com/ggobi/ggally/issues/448#issuecomment-1271581837_
      

----------

@larmarange
> Should we make a `{ggcoef}` package and reexport within {GGally}?

Sorry that I've been slow on releases. Yes, you do a great job fixing bugs very quickly. I'd be happy to reexport any methods from this R package. 

Example syntax
```r
#' @export
PACKAGE::METHOD
```

If you'd like for me to wait on releasing `{GGally}` so that your new package re-exports can be made, let me know. 😃

**Comment by larmarange** [comment]
Hi @schloerke 

I have drafted a first version of `ggcoef` package: https://github.com/larmarange/ggcoef

I still need to check compatibility with the next version of `ggplot2` but it should be possible to submit a first version of CRAN within 7 to 10 days. In that case, we could reexports the function directly in `GGally`.

Do you want me to include `stat_prop()`, `stat_weighted_mean()` and `stat_cross()` within `ggcoef`? They are not required for `ggcoef_model()` but it would also facilitate their maintenance.

**Comment by schloerke** [comment]
Wow. So fast! 

I like the idea of your `stat_**()` methods also being under your control. 

While the quick suggestion of `{ggcoef}`, I don't know if you'd like to make the name more generic. But if the stat methods are _kinda_ related to `{ggcoef}`, then `{ggcoef}` is a great package name.

**Comment by larmarange** [comment]
Not really related.

ggstats maybe ?

Joseph Larmarange

Le ven. 7 oct. 2022 à 19:39, Barret Schloerke ***@***.***> a
écrit :

**Comment by larmarange** [comment]
Hadley developed a ggstat package at some point.

Always difficult to find a generic name

Joseph Larmarange

**Comment by larmarange** [comment]
Well. Not published on cran and last commit in 2016...

Joseph Larmarange

**Comment by schloerke** [comment]
`{ggstats}` sounds good to me! (If he hasn't published it by now, then it's his own fault. haha)

**Comment by schloerke** [comment]
@larmarange You may be interested in #453 in the upgrade of using `{vdiffr}` and cosmetic changes for `{lintr}` lints. 

I couldn't get the right arrangement of what is being ignored and still able to be tested. I'll finish it up on Tuesday.

**Comment by larmarange** [comment]
Thanks a lot. 
The package has been renamed `ggstats`. 
I have included the code of the stats.
The code has been cleaned with `lintr`.
I have switched to `vdiffr` for the tests.

All tests seems OK.

Will now check the new release of `ggplot2`.

**Comment by larmarange** [comment]
Hi, `ggstats` is almost ready for submission on CRAN

I have checked the package with the next version of `ggplot2`. The only issue was the use of `aes_string()` now deprecated. I have updated the code, tested it with the next version of `ggplot2` and then with the current version of `ggplot2`. Everything seems OK. It has also been the opportunity to test the snapshot review process introduced with `vdiffr`.

If it is OK for you, I could submit a first version on CRAN. Then it would be possible to update `GGally` to simply imports functions from `ggstats`.

**Comment by larmarange** [comment]
I have the pleasure to inform you that ggstats is now on cran

**Comment by schloerke** [comment]
(Sorry I missed the earlier messages!)

Congrats on the package!! Very exciting!!

If you could make a PR to GGally similar to https://github.com/rstudio/shiny/blob/cda59da698eba1deda20ba09ca8b7f0b0b149f87/R/reexports.R#L7-L15 reexporting the `{ggstats}` methods, that would be great! (Any non-exported helper functions can also be removed.)

While I may be slow to respond, any time I can provide any help for `{ggstats}`, please let me know.

**Comment by larmarange** [comment]
No problem

I will prepare a PR this week

**Comment by larmarange** [comment]
See proposal in #455 

I have some questions regarding some vignettes:

- http://ggobi.github.io/ggally/articles/ggcoef_model.html
- http://ggobi.github.io/ggally/articles/ggally_stats.html

There are 3 options:

- keep them as they currently are
- remove the content and add a text inviting users to look at them on `ggstats` doc website, e.g. <https://larmarange.github.io/ggstats/articles/ggcoef_model.html>
- remove them completely

@schloerke do you have any preference?

**Comment by schloerke** [comment]
I like option # 2 . I will make a PR to HTML redirect to your vignettes from within `{GGally}`.

**Comment by larmarange** [comment]
Thanks. So do you want to merge #455 before updating the vignettes or should I update the PR?

Please note that for the stats vignette, it has been divided into 3 vignettes on ggtstats website: 

- https://larmarange.github.io/ggstats/articles/stat_cross.html
- https://larmarange.github.io/ggstats/articles/stat_prop.html
- https://larmarange.github.io/ggstats/articles/stat_weighted_mean.html

Regards
