### ISSUE TITLE
Warning message: The dot-dot notation (`..scaled..`) was deprecated in ggplot2 3.4.0.

### ISSUE THREAD

**Issue by costa-r** [ggobi/ggally#467]
---

Once I run the following code in order to create a scatmat matrix I get this warning message:
The dot-dot notation (`..scaled..`) was deprecated in
ggplot2 3.4.0.
ℹ Please use `after_stat(scaled)` instead.
ℹ The deprecated feature was likely used in the GGally
  package.
  Please report the issue at
  <https://github.com/ggobi/ggally/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where
this warning was generated. 

It seems to me the function that was deprecated is some function running in the background of ggscatmat() because I have not specifically called it. The matrix that is created seems to be correct though. I can't tell how much of a problem it really is but R asked me to report it here so that's what I did. If somebody has any advice on how to go around this issue without going too deep into what is happening behind the scenes, I would be happy to hear it. 

```r
sca_apq_check_scatmat <- GGally::ggscatmat(apq_apq156_ctq_metscaagg_full_df, columns = c("mean_resp", "apqg_iv", "apqg_pp", "apqg_pm", "apqg_id", "apqg_cp")) +
  theme_minimal()
```

**Comment by dicook** [comment]
Thanks @costa-r ! Fixed
