### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by schloerke** [ggobi/ggally#468]
@dicook I believe it is long overdue that I transfer maintainer role to someone else who can give more attention than my non-existent presence.

Would you like to the be the new maintainer? Should we ask [larmarange](https://github.com/larmarange)? [Contributors link](https://github.com/ggobi/ggally/graphs/contributors)

**Comment by schloerke** [comment]
Related but not required: #469 (Need a release by 2023-07-19)

**Comment by dicook** [comment]
I can’t be the maintainer. Most of the code is yours. There is also a lot of contributed code. The core functionality is the scatterplot matrix and it is very widely used. I recommend cutting any parts that break the CRAN checks to focus on the pairs plot functionality. Sent from my iPhoneOn 7 Jul 2023, at 2:33 am, Barret Schloerke ***@***.***> wrote:﻿
Related but not required: #469 (Need a release by 2023-07-19)
