### ISSUE TITLE
Allow parallel sets into parallel coordinates?

### ISSUE THREAD

**Issue by steltenpower** [ggobi/ggally#473]
RFE, but I'm all open to a better way or place to realize the following idea that I think is useful to many.

Parallel sets and parallel coordinates are both a great way to have an overview of your data, reorder columns, flip axes up-side-down and filter.
But, what if you could combine them, into one generic tool, from which you can also generate SQL?
Best I came up with so far: calculate set values into coordinate values (spread them evenly). That functionality to add here?

**Comment by schloerke** [comment]
Hi @steltenpower ! Thank you for the idea, but GGally does not work with SQL data directly nor export any SQL commands. So I would like to keep that door closed.

Best,
Barret
