### ISSUE TITLE
Migrate off reshape?

### ISSUE THREAD

**Issue by MichaelChirico** [ggobi/ggally#475]
Is there any reason besides inertia to keep using {reshape} as an Import? Any interest in migrating to `reshape2::melt()`, `data.table::melt()`, or `tidyr::pivot_longer()`?

**Comment by dicook** [comment]
I think it is because a data set from reshape it being used, see
data(tips, package = "reshape")

oh, but also see thar ggcorr uses melt. 

These should be easy to fix.

**Comment by MichaelChirico** [comment]
From what I can tell, the data set is only used in examples/tests/vignettes, maybe a target to put reshape in Suggests is easier than finding a new+suitable data set?

**Comment by dicook** [comment]
this data is available in many places, and I put it together originally. So it is easy enough to embed that data in the package itself. I’ll try to make the change in the next few days.

> On 19 Oct 2023, at 9:56 am, Michael Chirico ***@***.***> wrote:
> 
> 
> From what I can tell, the data set is only used in examples/tests/vignettes, maybe a target to put reshape in Suggests is easier than finding a new+suitable data set?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>

cheers,
Di


---
Dianne Cook
***@***.***

**Comment by MichaelChirico** [comment]
All the better then! No rush at all btw, low priority & get to it when you can. Thanks!

**Comment by dicook** [comment]
Fixed, but it would be good to remove dependence on plyr in ggparcoord.
