### ISSUE TITLE
datetime variables

### ISSUE THREAD

**Issue by stefanfritsch** [ggobi/ggally#57]
Hi,

ggpairs doesn't work with the datetime scale. Given that it is just a continuous scale with fancy labeling it should work but it results in the error:

```R
Error in Math.difftime(1816, base = 10) : 
  'log' not defined for "difftime" objects
```

I assume that is a known limitation? Otherwise I'd gladly provide a MWE. :)

Thx
Stefan

GGally 0.5.0 on R 3.1.2

**Comment by schloerke** [comment]
Hi Stefan,

Can you provide the example you were working with?  This is the first I've heard of dates not working... not that I've tried.

- Barret

**Comment by stefanfritsch** [comment]
Hi Barret,

Here's a MWE:

```R
library(data.table)
library(lubridate)

library(GGally)

X<-data.table(date=seq(ymd("2000-01-01"),
                       ymd("2010-12-31"),
                       ddays(1)))
X[,c("x","y"):=list(runif(.N),
                 rnorm(.N))]

pairs(X)
ggpairs(X)
```

pairs works, ggpairs results in the error above.

The problem is the following line in labeling::extended

```R
z <- ceiling(log(delta, base = 10))
```

I don't know how ggplot does its equivalent because there it works, but if you look at the debug output it seems like you lost the info that it's a datetime while if you build a simple ggplot it retains a parameter scale_name="datetime":

```R
p<-ggplot(X,aes(date,y)) +
  geom_point()

q<-ggplot_build(p)

q
```

```
...
$x_scales
$x_scales[[1]]
continuous_scale(aesthetics = aesthetics, scale_name = "datetime", 
    palette = identity, breaks = breaks, minor_breaks = minor_breaks, 
    expand = expand, trans = "time", guide = "none")
...
```


ciao
Stefan

**Comment by schloerke** [comment]
Yup, it's treating it as a factor, not a date.

**Comment by schloerke** [comment]
How would correlation work with a date variable and x?  Plotting is fine... just don't know about correlation.  

Make a "blank" plot for now, when doing correlation between a date and continuous variable?

**Comment by schloerke** [comment]
With punting on correlations, it seems to work out well.

```{r}
set.seed(123)
x2 <- X
x2$cat <- sample(c("a", "b", "c"), nrow(x2), replace = TRUE)

ggpairs(
  x2, c(2,1,4,3), color = "cat", 
  diag = list(continuous = "density"), 
  upper = list(continuous = "cor", combo = "box"), 
  lower = list(continuous = "points", combo = "dot")
)
# Can not calculate correlation of 'Date' variables.  Returning a 'blank' plot
# Can not calculate correlation of 'Date' variables.  Returning a 'blank' plot
```
![screenshot 2015-01-26 12 59 01](https://cloud.githubusercontent.com/assets/93231/5905128/d21b3604-a55b-11e4-9151-e6ceff73a4e9.png)

```{r}
ggpairs(
  x2, c(2,1,4,3), color = "cat", 
  diag = list(continuous = "bar"), 
  upper = list(continuous = "density", combo = "facethist"), 
  lower = list(continuous = "smooth", combo = "facetdensity")
)
```
![screenshot 2015-01-26 12 59 28](https://cloud.githubusercontent.com/assets/93231/5905132/d60a8c6a-a55b-11e4-9c4f-d6745cbf247a.png)

```{r}
ggpairs(
  x2, c(1,4), color = "cat", 
  diag = "blank", 
  upper = "blank",
  lower = list(combo = "denstrip"), 
)
```
![screenshot 2015-01-26 13 04 01](https://cloud.githubusercontent.com/assets/93231/5905133/d947a548-a55b-11e4-8caf-e11c9bbd0e7d.png)

**Comment by stefanfritsch** [comment]
Hmm, the correlation with the date variable would tell you about the linearity of the trend.

But I'm also happy with a blank plot. :)

Thx,
Stefan

**Comment by schloerke** [comment]
I was thinking of covariance and all of it's issues of minDate, maxDate, etc.  They don't matter for correlation.  I'll add it in.

**Comment by schloerke** [comment]
Added! 

```{r}
library(data.table)
library(lubridate)

load_all(); library(GGally)

set.seed(123)

X<-data.table(
  date = seq(ymd("2000-01-01"), ymd("2010-12-31"), ddays(1))
)

X[,c("x","y"):=list(runif(.N),rnorm(.N))]

x2 <- X
x2$cat <- sample(c("a", "b", "c"), nrow(x2), replace = TRUE)

ggpairs(
  x2, c(2,1,4,3), color = "cat", 
  diag = list(continuous = "density"), 
  upper = list(continuous = "cor", combo = "box"), 
  lower = list(continuous = "points", combo = "dot")
)
```
![screenshot 2015-01-30 15 33 25](https://cloud.githubusercontent.com/assets/93231/5982829/71d5ca4c-a895-11e4-9008-5e10dae37b01.png)

**Comment by vspinu** [comment]
Folks, this is still not working with the same error:

```
> X$cat <- sample(c("a", "b", "c"), nrow(X), replace = TRUE)
> 
> ggpairs(X,
+         upper = list(continuous = "density", combo = "box"),
+         lower = list(continuous = "smooth", combo = "dot"))
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
Error in Math.difftime(1339, base = 10) (from labeling.R#307) : 
  'log' not defined for "difftime" objects
> 

> ggpairs(X,
+         upper = list(continuous = "density", combo = "facethist"),
+         lower = list(continuous = "smooth", combo = "facetdensity"))
stat_bin: binwidth defaulted to range/30. Use 'binwidth = x' to adjust this.
Error in Math.difftime(1339, base = 10) (from labeling.R#307) : 
  'log' not defined for "difftime" objects
> 
```

**Comment by vspinu** [comment]
Ah. Ok. I just noticed you are developing on a `dev` branch. Works as expected.
