### ISSUE TITLE
ggpairs: no possibility to change axis and variable label font sizes

### ISSUE THREAD

**Issue by ghost** [ggobi/ggally#6]
Right now when using ggpairs for drawing > 4*4 scatterplot matrices, the axis and variable labels on diagonal become very small for printing purposes. Is it possible to adjust the font size in ggpairs()?

I already attempted to adjust the font size directly in ggally_diagAxis and ggpairs functions but with no success. The hard-coded font changes work when diagAxis is called independently but not when called by ggpairs.

**Comment by heshca** [comment]
I'm attempting to alter the variable name font size, as well, and am having no luck with the ```+ theme_grey(base_size = 8)``` method (nothing changes). When I attempt to add something like ```params=list(size=4)``` to the ```diag``` argument I get an error that ggpairs can't find the first object (variable) in my list of variables to put in the scatterplot. 

```
Error in ggally_diagAxis(ggally_data, ggplot2::aes(x = LOS, colour = Outcome),  : 
  object 'LOS' not found
Calls: <Anonymous> ... getPlot -> eval_ggpair -> eval -> eval -> ggally_diagAxis
```

Right now the plot looks like this:

![screenshot 2015-04-22 11 11 52](https://cloud.githubusercontent.com/assets/412996/7278003/f79c1042-e8e0-11e4-9e3f-0eb18870e128.png)

Code used to make the above plot:

```
ggpairs(data, c(7,9,11,13,14,16,20,21,24,25,26), upper = list(params=list(size=2)), legends = TRUE, lower = list(continuous = "points", discrete="facetbar"), diag = list(continuous = "density", discrete="facetbar", axisLabels = "internal", colour = "Outcome", title = "Scatterplot Matrix: Expanded Data")
```

**Comment by dicook** [comment]
Chris,

There are two many pairs of variables to be able to see much in the scatterplot matrix.

Since your data is numeric, you can use the simpler function ggscatmat, in GGally. It may make something slightly more manageable.

cheers,
Di

> On Apr 22, 2015, at 10:17 AM, Christopher Hesh <notifications@github.com> wrote:
> 
> I'm attempting to alter the variable name font size, as well, and am having no luck with the + theme_grey(base_size = 8) method (nothing changes). When I attempt to add something like params=list(size=4) to the diag argument I get an error that ggpairs can't find the first object (variable) in my list of variables to put in the scatterplot.
> 
> Error in ggally_diagAxis(ggally_data, ggplot2::aes(x = LOS, colour = Outcome),  : 
>   object 'LOS' not found
> Calls: <Anonymous> ... getPlot -> eval_ggpair -> eval -> eval -> ggally_diagAxis
> 
> Right now the plot looks like this:
> 
> 
> 
> Code used to make the above plot:
> 
> ggpairs(data, c(7,9,11,13,14,16,20,21,24,25,26), upper = list(params=list(size=2)), legends = TRUE, lower = list(continuous = "points", discrete="facetbar"), diag = list(continuous = "density", discrete="facetbar", axisLabels = "internal", colour = "Outcome", title = "Scatterplot Matrix: Expanded Data")
> 
> —
> Reply to this email directly or view it on GitHub.
> 

---------------------------
Di Cook
visnut@gmail.com

**Comment by heshca** [comment]
Di,

True, it's not a terribly useful plot. It's just an example of variable titles not fitting in the diagonal boxes without any ability to change the font.

- Christopher

**Comment by dicook** [comment]
I should have made this package a google summer of code project %^) Could have made lots of little fixes, and created some new routines! Next year!

> On Apr 22, 2015, at 10:54 AM, Christopher Hesh <notifications@github.com> wrote:
> 
> Di,
> 
> True, it's not a terribly useful plot. It's just an example of variable titles not fitting in the diagonal boxes without any ability to change the font.
> 
> 	• Christopher
> —
> Reply to this email directly or view it on GitHub.
> 

---------------------------
Di Cook
visnut@gmail.com

**Comment by f4bry** [comment]
Hi Chris,
Have you found a solution?
I would like to increase the size of the upper part corr labels.
Thanks!
Fab

**Comment by schloerke** [comment]
Hi Fab,

With the current master branch / CRAN version (1.0.1) ...

```{r}

# the 'wrap' function changes the default behavior of a function.
# with this function, we are allowed to supply specific arguments.

wrap("cor") # functionally the same ggally_cor
wrap("cor", size = 3) # runs ggally_cor, but sets the arg size to 3

head(ggally_cor, 3)
# 1 function (data, mapping, alignPercent = 0.6, method = "pearson",    
# 2     use = "complete.obs", corAlignPercent = NULL, corMethod = NULL, 
# 3     corUse = NULL, ...)  

# We can change the size and alignment with 'size' and 'alignPercent' respectively

# original (or something equivalent)
# bad size and shifted too far to the left
ggpairs(
  iris, 1:4, mapping = aes(color = Species), 
  upper = list(
    continuous = wrap("cor")
  )
)
```
![screen shot 2016-05-20 at 11 14 47 pm](https://cloud.githubusercontent.com/assets/93231/15446104/2362ec54-1ee2-11e6-8404-1c68cccd6ac0.png)

```{r}
# new, better plot (for my print size)
ggpairs(
  iris, 1:4, mapping = aes(color = Species), 
  upper = list(
    continuous = wrap("cor", size = 4.75, alignPercent = 1)
  )
)
```
![screen shot 2016-05-20 at 11 17 52 pm](https://cloud.githubusercontent.com/assets/93231/15446105/331529be-1ee2-11e6-989c-399646c336f1.png)


As a reminder, you are allowed to supply a custom R function that produces a ggplot2 object instead of the "cor" string.

**Comment by f4bry** [comment]
Hi schloerke,

Sorry but I don't have the wrap function. Should I install a specific package?
Thank you!
Fab

**Comment by schloerke** [comment]
Installing the latest version of GGally (version 1.0.1) should fix this.  After installing, restart R to make sure the new package is loaded.

**Comment by f4bry** [comment]
Nice!Thank you very much!
Fab

**Comment by f4bry** [comment]
sorry, one more thing: can we add transparency to the density plots on the diagonal?
Thanks!
Fab
