### ISSUE TITLE
spearman corMethod

### ISSUE THREAD

**Issue by schloerke** [ggobi/ggally#60]
I'm trying to use the corMethod parameter (from ggally_cor via ggpairs) to set the correlation method from pearson to spearman

ggpairs(.....
            lower=list(continuous="cor", corMethod="spearman", combo="dot", discrete="facetbar", params=c(cex = 3) ),
...)

the corMethod="spearman" seems not to be honored, instead giving pearson correlations.

looking into the source I see:
>ggally_cor
...
function (data, mapping, corAlignPercent = 0.6, corMethod = "pearson", 
    corUse = "complete.obs", ...) 
{
    corMethod <- as.character(substitute(corMethod))
...

however the transformation as.character(substitute(...  seems to be modifying corMethod to be 'corMethod'

>corMethod="spearman"
> as.character(substitute(corMethod))
[1] "corMethod"

Is this what is desired? is something more complicated being passed to ggally_cor as corMethod?

- Nathan

**Comment by schloerke** [comment]
fixes issue: ba78b8e61320ac20442d92db510603dc9beebde9

**Comment by jclopeztavera** [comment]
Hi Natan, 

I'm still having the same issue calling:
 
```
ggpairs(data, ... , upper = list(continuous = "cor", corMethod = "spearman"))
```
Still prints the Pearson correlations.

**Comment by daxiagithub** [comment]
I'm having the same issue.

**Comment by schloerke** [comment]
Currently on github master branch....

```{r}
cor(iris$Sepal.Length, iris$Sepal.Width, method = "pearson")
# [1] -0.1175698
cor(iris$Sepal.Length, iris$Sepal.Width, method = "spearman")
# [1] -0.1667777

ggpairs(
  iris, 1:3, 
  upper = list(
    continuous = wrap('cor', method = "spearman")
  ), 
  lower = list(
    continuous = 'cor'
  )
)
```
![screen shot 2015-11-11 at 2 21 56 pm](https://cloud.githubusercontent.com/assets/93231/11100489/9a1e71be-887f-11e5-8e7d-a22961102eab.png)

Release date was to be this Friday, Nov 13.  Due to ggplot2 being pushed back, GGally is being pushed back as well.  The new ggplot2 (and consequently GGally)  CRAN release date is December 11. 

For now, please install the github version of ggplot2 and GGally.
```{r}
library(devtools)
install_github("hadley/ggplot2")
install_github("ggobi/ggally")
```

**Comment by daxiagithub** [comment]
Thank you for the update!
