### ISSUE TITLE
test coverage for ggnet

### ISSUE THREAD

**Issue by schloerke** [ggobi/ggally#65]
Hey @briatte! Is it possible for you to add some tests for ggnet?  

I do not know how to reach all of the awesome features.

My typical workflow for testing a specific function:

```{r}
library(devtools); library(testthat)
library(covr); # install_github("jimhester/covr")

#See percentage
load_all(); function_coverage("ggnet", test_file("tests/testthat/test-ggnet.R"))
# Loading GGally
# ggnet : .........
# 
# Package Coverage: 64.20%
# ./R/ggnet.R: 64.20%

# See missing lines
load_all(); zero_coverage(function_coverage("ggnet", test_file("tests/testthat/test-ggnet.R")))
# Loading GGally
# ggnet : .........
# 
#                                                      filename first_line
# 1  /Users/barret/Copy/git/R/ggobi_org/ggally/ggally/R/ggnet.R        105
# 2  /Users/barret/Copy/git/R/ggobi_org/ggally/ggally/R/ggnet.R        124
# ...
#    last_line value
# 1        105     0
# 2        126     0
# ...
```

Thank you!

**Comment by briatte** [comment]
Dear @schloerke – sure, I can take a look (never wrote tests before but it seems straightforward).

Beginner's question: why won't the `dev` branch fork properly? When I fork + clone the repo, only the `master`, `cor_test` and `ggsurv` branches show up.

**Comment by schloerke** [comment]
``ggsurv`` branch is old.  So, something seems wrong.  

Want to follow [these directions](https://github.com/ggobi/ggally/pull/44#issuecomment-68557615)?  It may help.  

If you don't mind pasting the output of ``git branch -avv``? I'm guessing you'll need to do something similar to ``git fetch ggobi``.

**Comment by briatte** [comment]
Instructions helped a lot (I only use Git through the app):

```
Zoidberg:ggally fr$ git remote add upstream "https://github.com/ggobi/ggally.git"
Zoidberg:ggally fr$ git fetch upstream
From https://github.com/ggobi/ggally
 * [new branch]      cor_test   -> upstream/cor_test
 * [new branch]      dev        -> upstream/dev
 * [new branch]      master     -> upstream/master
 * [new branch]      params     -> upstream/params
 * [new branch]      tests      -> upstream/tests
Zoidberg:ggally fr$ git branch -vv
* master 150077c [origin/master] bumped date
Zoidberg:ggally fr$ git fetch upstream
Zoidberg:ggally fr$ git checkout -b dev upstream/dev
Branch dev set up to track remote branch dev from upstream.
Switched to a new branch 'dev'
Zoidberg:ggally fr$ git checkout dev
Already on 'dev'
Your branch is up-to-date with 'upstream/dev'.
```

I'll need a bit of time (teaching 6 hrs/day for the next two weeks), but will add tests next month.

**Comment by briatte** [comment]
Hi @schloerke,

I'm working on a rewrite of `ggnet`: [here's the vignette](http://f.briatte.org/temp/ggnet-vignette.html). This is a complete rewrite that drops some existing arguments that do not really belong in a network visualization function, and changes the behaviour of other arguments. Is it alright if I push a new version that badly breaks previous ones?

**Comment by schloerke** [comment]
With the old arguments, can you make sure to have something along the lines of "stop('deprecated argument')" ?  Thank you. 

Make sure your version runs smoothly with devtools::check('./'). I'll be working on making a longb overdue release on Monday/Tuesday. 

Please put a pull request to the Dev branch. 

Thank you!

**Comment by briatte** [comment]
@schloerke tests for `ggnet` submitted

Do you mind if I submit the new version of `ggnet` as `ggnet2`? The internals are completely different and break too many things.

**Comment by schloerke** [comment]
Sounds good to me. Thank you!

**Comment by briatte** [comment]
The new code in the `dev` branch closes this issue.
