### ISSUE TITLE
ggcorr: make color continuous

### ISSUE THREAD

**Issue by maxheld83** [ggobi/ggally#67]
... maybe as an option?

Since the corellation coefficients *are*, in fact, continuous information.

(Duplicate posting to https://github.com/briatte/ggcorr/issues/3 – wasn't sure whether that repo was still active)

**Comment by schloerke** [comment]
@briatte Does this sound ok to you?  

Seems reasonable to me.  I'd even like to make this default behavior.

-Barret

**Comment by briatte** [comment]
@maxheld83 @schloerke Yes, sounds okay, although it will require some work. I'm tracking the issue at [briatte/ggcorr#3](https://github.com/briatte/ggcorr/issues/3).

**Comment by schloerke** [comment]
@briatte Ok.  Let me know if I can help.  

(Please pull latest from dev.  I believe some changes have been made).

**Comment by schloerke** [comment]
merged a long time ago
