### ISSUE TITLE
ggparcoord warning: number of items to replace is not a multiple of replacement length

### ISSUE THREAD

**Issue by ziyuang** [ggobi/ggally#76]
The 160x15 test data can be downloaded [here](http://pastebin.com/NQtYAnFJ).

`ggparcoord` fails to produce a PCP with all 15 axes with most of the ordering methods, except for `Skewed`.

Also in all cases, the warning

    In a[k + 1] <- d.scag[1, 1:2][!(a[k] == d.scag[1, 1:2])] :
      number of items to replace is not a multiple of replacement length

can be seen.

**Comment by schloerke** [comment]
From the dev branch, this works without warning/error.

```{r}
dt <- read.table(url("http://pastebin.com/raw.php?i=NQtYAnFJ"), header = FALSE)
ggparcoord(dt, order = "Skewed")
```
![screenshot 2015-09-09 17 05 22](https://cloud.githubusercontent.com/assets/93231/9774204/fafb0b4c-5714-11e5-93a1-e747d6ca8b2b.png)

I do see an warning in the master branch.  Sorry for the delay.

**Comment by ziyuang** [comment]
Please try this again:

    dt <- read.csv(url("http://pastebin.com/raw.php?i=3FM83zDb"))
    ggparcoord(dt, order = "Skewed")
