### ISSUE TITLE
diagonal bar invalid when summarizing negative values

### ISSUE THREAD

**Issue by tsieger** [ggobi/ggally#78]
Summarizing negative values using ggpairs with `diag=list(continuous='bar')` yields a spurious plot (I would expect a histogram, but the diagonal plots show bars going below the axis). Maybe, I'm missing something (?).

To reproduce:
```
set.seed(0)
x<-data.frame(x1=c(rnorm(100),rnorm(10,5)),x2=c(rnorm(100),rnorm(10,5)))
ggpairs(x,diag=list(continuous='bar'))
```
Note:
Warning messages:
1: In loop_apply(n, do.ply) : Stacking not well defined when ymin != 0
2: In loop_apply(n, do.ply) : Stacking not well defined when ymin != 0

![bug2_bad](https://cloud.githubusercontent.com/assets/1840074/7249217/205a08d6-e819-11e4-960e-919ac27d6436.png)

**Comment by schloerke** [comment]
The original intent was to pass on the Y axis to the other plots done horizontally.  I know it's not lining up perfectly, but it should give you a hint as to where Y axis is for the upper right plot. ![screenshot 2015-09-09 16 24 00](https://cloud.githubusercontent.com/assets/93231/9773226/34742742-570f-11e5-8ea7-e99385d19cad.png)


That being said, the counts obviously don't make sense.

```{r}
pm <- ggpairs(x,diag=list(continuous='bar'), upper = list(continuous = 'points'))
pm
```
![screenshot 2015-09-09 16 24 00](https://cloud.githubusercontent.com/assets/93231/9773358/c830a9ba-570f-11e5-8219-bb6e7802fadf.png)


You can see the plot has been rescaled on the Y axis.
```{r}
getPlot(pm,1,1)
```
![screenshot 2015-09-09 16 27 50](https://cloud.githubusercontent.com/assets/93231/9773367/d383d04e-570f-11e5-8fbb-015e6be04b13.png)


I believe I should add a parameter to not rescale the data. for situations like these.  

This situation would not occur if 
* all data was positive
* categorical data was in the first column

**Comment by schloerke** [comment]
a5c43ea35ff347a9fb910a03db8e1436a9d76380
