### ISSUE TITLE
Is there going to be a release any time soon?

### ISSUE THREAD

**Issue by elbamos** [ggobi/ggally#82]
Looks like a bunch of stuff (like the code I contributed) has been merged but is still sitting in dev?

**Comment by schloerke** [comment]
Sorry for the massive delay. My advisor said to drop everything and study. However, I just passed quals! Yay!

I'll be working on making a major release Monday/Tuesday.

**Comment by elbamos** [comment]
Let me know if I can help!

**Comment by schloerke** [comment]
My weekend is cleared out, so I'll be working on the rest of the package to get it ready for the ggplot2 update.

I'd like to do a release along side ggplot2 for Nov 13th.  Since this is the case, things should be ready to go by Oct 30th.  This allows 2 weeks for depends to update.

**Comment by schloerke** [comment]
*Emails sent to revdep maintainers

**Comment by schloerke** [comment]
"
Hi all,

I was planning on submitting the next version of ggplot2 to CRAN on
Friday, but it looks like there are too many problems with existing
packages. The new release target will be Dec 11.

...
Hadley
"

So I guess we wait

**Comment by schloerke** [comment]
... still waiting on Hadley. It's best to have ggplot2 up on CRAN to make everything pass. Need the CRAN ggplot2 update to pass build_win() check and possibly make other packages install.

GGally passes local release checks and cran comments are ready.

**Comment by schloerke** [comment]
Submitted to CRAN.  Waiting on success or alterations.

**Comment by schloerke** [comment]
---------- message ---------
From: Uwe Ligges
Date: Wed, Dec 30, 2015 at 6:36 PM
Subject: Re: CRAN submission GGally 1.0.0
To: Barret Schloerke, CRAN


Thanks, on CRAN now.

Best,
Uwe Ligges
