### ISSUE TITLE
How to change line width?

### ISSUE THREAD

**Issue by SamGG** [ggobi/ggally#83]
Nice package. I would like to tune the line width. Any idea?

**Comment by schloerke** [comment]
check out the last part of the examples of ggpairs ```examples(ggpairs)```.  It shows how to do custom plots.  

Also you may do...
```{r}
library(GGally)
data("tips", package = "reshape")
ggpairs(tips, 1:3, diag= list(params = c(size = 10)))
```
![screenshot 2015-09-02 17 09 39](https://cloud.githubusercontent.com/assets/93231/9644671/76193612-5195-11e5-89d4-2d50f42ebf20.png)


The same idea applies to the ```upper``` or ```lower``` arguments of ```ggpairs```
