### ISSUE TITLE
str_c vs. paste, str_detect vs. grepl

### ISSUE THREAD

**Issue by briatte** [ggobi/ggally#95]
`GGally` imports `stringr` for two functions, `str_c` and `str_detect`.

Any particular reason why `paste`, `paste0` and `grepl` are not sufficient here? They should be, unless there's some vectorisation needed.

Since `stringr` relies on `stringi`, it's quite a heavy import (unlike `reshape` which is a lightweight one; re #92). I very much like `stringr` and `stringi`, but I'm thinking in streamlining terms here.

**Comment by schloerke** [comment]
I made an internal wrapper.  The familiarity of str_* is very comforting. :-)

6dbf07b
